Seregost = "49.0s,33.0e" 
Sg = "Seregost"
Sgl = "Seregost: "
Tg = "Thikil-gundu"
Gd = "Glimmerdeep"
Nb = "Naerband"
Naerband = "63.8s,18.5e"
HuM,HuML = "Hall under Mtn","14.7n,135.2w"
TU = "Torech Ungol@61.4s,4.6e"
TUn = "Must finish 'She Who Walks in the Darkness' to enter Torech Ungol."
Fg = "Felegoth"
Fix = {["the North"]="Strongholds"}
Pl = "place "
TC = "Treasure Cache"
Tc = "Treasure Chest"
RMC = "Rare Mordor Chest"
Region = { Eriador=1, Rhovanion=2, ["Tales of Yore"]=2, Gondor=3, Mordor=4, Haradwaith=5 }
Atype = {D="Deed", Q="Quest"}
Reward = { B="Barter items", C="Coins", D="Decor", I="Legendary Item Exp",
		L="LOTRO points", M="Marks", O="Other", R="Reputation", 
		S="Steed Exp.", T="Title", V="Virtue Exp." }

Lore = {
    ["Instances"] = {
        ["Shadows of Angmar"] = {
            ["Urugarth"] = {d=Pl, t='D', r=1, R='LVR',
                c="Instances/Shadows of Angmar/The City of Orcs", 
                p={ {"901n,32.1w","Dushkal's Lair"},
                    {"9.0n,30.2w","Lhugrien's Roost"},
                    {"9.8n,30.1w","Lagmas' Court"},
                    {"10.5n,31.2w","Fell-water Falls"},
                    {"10.2n,32.1w","Urugarth Kennels"},
                    {"8.8n,30.1w","Asht-shâpol"}
                },
            },
            ["Carn Dûm"] = {d=Pl, t='D', r=1, R='LVR',
                c="Instances/Shadows of Angmar/The Enemy's Stronghold", 
                p={ {"12.2n,34.3w","Slave-pens"},
                    {"11.9n,34.5w","Slave-pens"},
                    {"13.8n,32.6w","Barashal's Domain"},
                    {"12.6n,34.0w","Fell-water Source"},
                    {"11.7n,34.4w","Duvardain Quarter"},
                    {"14.0n,33.5w","Castle of Carn Dûm"},
                    {"14.3n,33.6w","Seat of the Witch King"},
                    {"14.0n,33.6w","Witch King's Watch"},
                },
            },
            ["Idols of Urugarth"] = {d=Pl, t='D', r=1, R='LTR',
                c="Instances/Shadows of Angmar/The Foul Idols of Urugarth",
                p={ {"10.7n,31.5w","North-western Foul Idol"},
                    {"10.3n,31.4w","Northern Foul Idol"},
                    {"9.1n,31.0w","Southern Foul Idol"},
                    {"9.0n,31.7w","South-western Foul Idol"},
                    {"9.0n,31.1w","Central Foul Idol"},
                },
            },
        },
        ["Mines of Moria"] = {
            ["The Grand Stair"] = {d=Pl, t='D', r=2, R='LTR',
                c="Instances/Mines of Moria/Landings of the Grand Stair",
                p={ {"71.8n,139.0w","Cave of the Slumbering Beast"},
                    {"71.9n,138.6w","Gothghaash's Stand"},
                    {"72.6n,138.2w","Throne of Igash"},
                    {"71.8n,137.8w","Nardur's Station"},
                    {"71.2n,137.6w","Highpeak Kennels"},
                },
            },
            ["Missing Dwarves in the Vile Maw"] = {d='npc', t='D', r=2, R='LTR',
                c="Instances/Mines of Moria/Lost to the Deeps",
                p={ {"21.0s,115.4w","Dwarf-miner"},
                    {"20.3s,155.2w","Dwarf-merchant"},
                    {"20.4s,115.2w","Dwarf-adventurer"},
                    {"20.7s,115.0w","Dwarf-warrior"},
                },
            },
        },
    },
    ["Angmar"] = {
        ["Outposts of the Free Peope"] = {d=Pl, l=40, t='D', r=1, R='LMVR',
            c="Eriador/Angmar/Bastions of Hope",
            s={["Aughaire"]="0.2s,39.3w",["Gabilshathur"]="3.6s,26.5w",["Iorelen's Camp"]="10.6n,15.5w",["Gath Forthnir"]="10.4n,24.0w"},
            p={ {"3.0s,39.1w","Lehmä-koti"},
                {"0.0n,40.0w","Aughaire"},
                {"1.9s,33.2w","Tyrn Lhuig"},
                {"3.6s,26.4w","Gabilshathûr"},
                {"10.8n,24.0w","Gath Forthnir"},
            },
        },
        ["Towers of Despair"] = {d=Pl, l=40, t='D', r=1, R='LMVR',
            c="Eriador/Angmar/The Circle of Despair",
            s={["Gath Forthnir"]="10.4n,24.0w"},
            p={ {"7.8n,23.0w","Minas Caul"},
                {"7.2n,23.2w","Minas Agar"},
                {"6.6n,22.9w","Minas Maur"},
                {"6.4n,22.4w","Minas Angos"},
                {"7.8n,21.8w","Minas Nir"},
                {"6.6n,21.8w","Minas Deloth"},
                {"7.1n,21.6w","Minas Gularan"},
                {"8.0n,22.4w","Minas Dhem"},
            },
        },
        ["Path to Carn Dum"] = {d=Pl, l=40, t='D', r=1, R='LMVR',
            c="Eriador/Angmar/The Road to War",
            s={["Aughaire"]="0.2s,39.3w",["Gabilshathur"]="3.6s,26.5w",["Iorelen's Camp"]="10.6n,15.5w",["Gath Forthnir"]="10.4n,24.0w"},
            p={ {"5.00s,36.6w","Skathmùr"},
                {"0.08n,34.25w","Bail Ròva"},
                {"3.20n,30.34w","Bail Boglakh"},
                {"3.38n,27.6w","Mor Maudhùl"},
                {"10.14n,28.10w","Bail Dilas"},
                {"12.007n,29.53w","Gate of Shadows"},
            },
        },
        ["Treasure of Angmar"] = {d=Tc, l=40, t='D', r=1, R='LMOVR',
            c="Eriador/Angmar/Treasure of Angmar",
            s={["Gath Forthnir"]="10.4n,24.0w"},
            p={ {"7.2n,30.4w","Imlad Balchorth - across the green death waters. Stepping stones located at 6.7N, 30.5W."},
                {"4.7n,29.2w","Imlad Balchorth - top of the stairs next to Iron Crown Spirit-master"},
                {"3.9n,39.9w","Nad Nathair - behind Bloodwing"},
                {"6.3n,37.9w","Dûn Covàd - by War-Master Ranghâsh"},
                {"12.2n,29.5w","Gate of Shadows"},
                {"12.1n,27.3w","Himbar - hole in wall west of entrance to spider area"},
                {"13.0n,25.4w","Torech-i-Bogbereth"},
                {"9.5n,22.9w","Nan-Guruth - north end of path. Main path towards Minas Caul; 8.1N, 23.1W take the narrow path to your left. Follow north to Dourhands, at fork, go right."},
                {"4.5n,21.1w","Nun-Guruth - end of dead-end ledge on south wall"},
                {"1.6s,23.2w","Gorothlad - rim SW of Krusle Lannan"},
                {"0.7s,36.5w","Ram Dùath - end of Cavern with Blade Beaks - follow path S from Aughaire to 1.9S, 39.0W, go downhill E towards lake, E with lake to right to get to cavern."},
                {"10.3n,14.3w","E of Iorelen's Camp near cliff and Orc Camp"},
            },
        },
        ["The Seven Swords"] = {d="sword", l=40, t='Q', r=1, R='LMTR',
        s={["Gabilshathur"]="3.6s,26.5w"},
            c="Eriador/Angmar/The Seven Swords",
            p={ {"1.8n,24.6w","Sword of Abb from Owen"},
                {"2.2n,25.6w","Sword of Kolmak from Ruraikh"},
                {"2.3n,27.8w","Sword of Ànraig from Tobaid"},
                {"3.7n,27.4s","Sword fo Guinokh from Brekhin"},
                {"0.6s,26.2w","Sword of Innis from Dugald"},
                {"0.9s,24.9w","Sword of Kevoka from Frangan"},
                {"0.4s,24.5w","Sword of Mànas from Huisdàn"},
            },
        },
        ["Roving Threats"] = {d='npc', l=40, t='Q', r=1, R='LMOTVR',
            c="Eriador/Angmar/Roving Threads: Angmar's Roving Enemies",
            s={["Aughaire"]="0.2s,39.3w",["Gabilshathur"]="3.6s,26.5w",["Iorelen's Camp"]="10.6n,15.5w",["Gath Forthnir"]="10.4n,24.0w"},
            p={ {"0.6n,35.9w","Fasach-larran - E of entrance to Morfil, S cliff"},
                {"4.8n,34.7w","Fasach-Falroid - NE of entrance to Bûrzum Pushdug"},
                {"2.2n,32.0w","N edge of Western Malenhad"},
                {"8.8n,28.7w","SW Himbar - near overlook of Imlad Balchorth"},
                {"0.8n,28.6w","Eastern Malenhad - W shore of lake Duvuinen"},
                {"0.9n,27.2w","Lake Duvuinen - island with Amardam"},
                {"11.3n,27.1w","N Himbar - near spider pit"},
                {"3.2n,24.2w","NE of Grishbalt - drop-off overlooking camp - approach from E"},
                {"5.7n,23.4w","SW Nan Gurth"},
                {"0.8n,20.8w","Gorothlad - E rim of Warg Pit"},
                {"7.1n,201.w","E Nan Gurth - E of Barad Gùlaran"},
            },
        },
        ["Hidden Threats"] = {d='npc', l=40, t='D', r=1, R='TR',
            c="Eriador/Angmar/Hidden Threats of Angmar",
            p={ {"13.0n,25.5w","Spider Lair of Torech-i-Bogbereth"},
                {"6.3n,29.6w","Barrow-grounds of Gurthlin"},
            },
        },
    },
    ["Bree-land"] = {
        ["Barrow Downs"] = {d=Pl, l=20, t='D', r=1, R='LMVR',
            c="Eriador/Bree-Land/The Barrow-downs",
            s={["West Bree"]="29.5s,52.7w"},
            p={ {"30.3s,56.0w","Northern Barrows"},
                {"32.1s,55.1w","The Dead Spire"},
                {"32.1s,53.8w","The Dead Man's Perch"},
                {"33.8s,55.8w","The Great Barrow"},
                {"35.6s,53.9w","Ost Gorthad"},
            },
        },
        ["The Old Forest"] = {d=Pl, l=15, t='D', r=1, R='LMVR',
            c="Eriador/Bree-Land/The Old Forest",
            s={["Adso's Camp"]="29.2s,56.6w",["Buckland"]="32.9s,61.8w"},
            p={ {"31.5s,59.0w","Bald Hill"},
                {"36.8s,57.8w","The Weaver's Den"},
                {"32.6s,57.3w","Tom Bombadil's House"},
                {"31.1s,59.4w","Goldberry's Spring"},
                {"32.8s,60.7w","Baonfire Glade"},
            },
        },
        ["Bree-Land"] = {d=Pl, l=1, t='D', r=1, R='LMVR',
            c="Eriador/Bree-Land/The Ruins of Bree-land",
            s={["Bronwe's Folly"]="28.6s,49.5w",["Adso's Camp"]="29.2s,56.6w",["Buckland"]="32.9s,61.8w",["West Bree"]="29.5s,52.7w",["Hengstacer Farm"]="22.3s,52.3w",["Combe"]="28.6s,49.5w",["South Bree"]="31.9s,50.4w"},
            p={ {"26.8s,48.0w","Bronwe's Folly"},
                {"26.7s,46.6w","Blackwold's Roost"},
                {"27.8s,58.7w","Hillshire Ruins"},
                {"24.0s,53.1w","The Old Greenway Fort"},
                {"26.6s,44.4w","Blackwold Headquarters"},
                {"29.4s,45.9w","Woodsedge Ruins"},
                {"33.3s,48.4w","Ost Baranor"},
                {"33.1s,42.9w","Goblinhole Ruins"},
                {"35.7s,51.5w","South-guard Ruins"},
            },
        },
        ["Flowers of Old Forest"] = {d='flower', l=15, t='D', r=1, R='LMVR',
            c="Eriador/Bree-land/Flowers of the Old Forest",            
            s={["Adso's Camp"]="29.2s,56.6w",["Buckland"]="32.9s,61.8w"},
            p={ {"32.0s,61.0w","Rhosthon's Flower"},
                {"30.6s,57.3w","Neldorlas' Flower"},
                {"34.2s,60.1w","Dorollin's Flower"},
                {"32.6s,59.3w","Cordofoneth's Flower"},
                {"33.3s,57.5w","Lenhwest's Flower"},
                {"35.2s,56.9w","Silloth's Flower"},
                {"32.2s58.4w", "Braiglad's Flower"},
                {"35.3s,58.3w","Merillif's Flower"},
            },
        },
        ["History of the Dùnedain"] = {d='relics', l=1, t='D', r=1, R='LMVR',
            c="Eriador/Bree-land/The History of the Dùnedain",
            s={["Bronwe's Folly"]="28.6s,49.5w",["Adso's Camp"]="29.2s,56.6w",["Buckland"]="32.9s,61.8w",["West Bree"]="29.5s,52.7w",["Hengstacer Farm"]="22.3s,52.3w",["Combe"]="28.6s,49.5w",["South Bree"]="31.9s,50.4w"},
            p={ {"33.4s,48.8w","Ost Baranor - Dùnedain Statue"},
                {"30.2s,49.1w","The Crumbled Court - Ancient Inscription"},
                {"27.1s,46.6w","Blackwold's Roost - Ancient Cairn"},
                {"30.7s,52.6w","Beggar's Alley - Bree - Ancient Crest"},
                {"31.2s,44.9w","Marshwater Fort - Ancient Altar"},
                {"29.5s,45.8w","Woodsedge Ruins - Ancient Obelisk"},
            }
        },
        ["Executioner of the Wicked"] = {d='npc', l=15, t='D', r=1, R='LTR',
            c="Eriador/Bree-land/Executioner of the Wicked",
            s={["West Bree"]="29.5s,52.7w"},
            p={ {"33.0s,55.4w","Hadh Nogbenn - Brishzel"},
                {"31.3s,54.7w","Ringdor - Umnen"},
                {"35.1s,55.1w","Haudh Iarchith - Fergandir"},
                {"33.7s,53.9w","Goetham - Faegfaer"},
                {"31.5s,55.5w","Haudh Methernil - Marrow"},
                {"30.9s,55.0w","Taradan - Gwigon"},
            },
        },
    },
    ["Dunland"] = {
        ["Carreglyn"] = {d=Pl, l=62, t='D', r=1, R='LMVR',
            c="Eriador/Dunland/Exploring Carreglyn",
            s={["Barnavon"]="84.7s,16.3w"}
            p={ {"84.9s,16.8w","Lower Barnavon"},
                {"84.9s,17.6w","Upper Barnavon"},
                {"81.9s,15.7w","Naur-maudhûl"},
                {"84.7s,14.4w","Barnavon Mine"},
                {"85.1s,15.1w","Hen Turrau"},
                {"86.0s,17.4w","Lhun Avanc"},
                {"83.9s,16.8s","Munfaeril's Shrine"},
            },
        },
        ["Pren Gwydh"] = {d=Pl, l=67, t='D', r=1, R='LMVR',
            c="Eriador/Dunland/Exploring Pren Gwydh",
            s={["Galtrev"]="79.9s,16.7w"},
            p={ {"79.2s,17.0w","The Fanged Lair"},
                {"80.2s,18.7w","Bloodtusk's Den"},
                {"78.9s,15.7w","The Galtrev Lumber-camp"},
                {"79.9s,19.5w","Dragon-clan Settlement"},
                {"78.2s,13.8w","The Howling Caverns"},
                {"79.5s,19.0w","Rook's Hut"},
            },
       },
        ["Starkmoor"] = {d=Pl, l=69, t='D', r=1, R='LMVR',
            c="Eriador/Dunland/Exploring Starkmoor",
            s={["Avardin"]="83.5s,20.4w"},
            p={ {"83.4s,20.7w","Avardin"},
                {"81.7s,18.2w","Flam-cadius"},
                {"81.3s,21.3.w","Cartrev Andras"},
                {"84.4s,18.9w","The Hound's Rest"},
                {"83.3s,21.4w","The Culling Pit"},
                {"87.7s,17.3w","Wulf's Cleft Overlook"},
            },
        },
        ["Bonevales"] = {d=Pl, l=62, t='D', r=1, R='LMVR',
            c="Eriador/Dunland/Exploring the Bonevales",
            s={["Echad Naeglanc"]="77.3s,15.8w"},
            p={ {"76.8s,15.0w","The bone Quarry"},
                {"76.1s,14.3w","Plas-maru"},
                {"77.3s,15.8w","Echad Naeglanc"},
                {"76.7s,18.2w","Lhan Bach"},
                {"75.8s,17.5w","Lhan Gogledh"},
            },
        },
        ["Dunbog"] = {d=Pl, l=62, t='D', r=1, R='LMVR',
            c="Eriador/Dunland/Exploring the Dunbog",
            s={["Lhan Rhos"]="86.8s,23.0w"},
            p={ {"84.0s,24.4w","Lhan Colvarn"},
                {"87.2s,23.2w","Lhan Rhos"},
                {"88.8s,23.81","The Withered Stones"},
                {"88.0s,25,7w","Durgors"},
                {"85.5s,25.7w","The Pristine Glade"},
            },
        },
        ["Trum Drengh"] = {d=Pl, l=66, t='D', r=1, R='LMVR',
            c="Eriador/Dunland/Exploring Trum Dreng",
            s={["Lhan Tarran"]="75.3s,22.4w"},
            p={ {"76.9s,23.0w","Dire Hollow"},
                {"79.2s,24.0w","The Herd-lands"},
                {"75.3s,22.7w","Lhan Tarran"},
                {"74.2s,21.4w","The North Pass"},
                {"76.2s,21.4w","The Watch-tower"},
                {"78.3s,21.2w","The White Hand Outpost"},
            },
        },
        ["Nan Curunìr"] = {d=Pl, l=66, t='D', r=1, R='LMVR',
            c="Eriador/Dunland/Exploring Nan Curunìr",
            s={["Dagoras' Camp"]="84.9s,3.5w"},
            p={ {"81.4s,2.5w","The Gates of Isengard"},
                {"84.9s,3.0w","Piller of the White Hand"},
                {"81.6s,4.8w","Fang-rider's Warren"},
                {"84.3s,1.6w","Blackmarch Fort"},
                {"82.0s,0.7e","Quickbeam's Grove"},
                {"84.9s,3.4w","Dagoras' Camp"},
            },
        },
        ["Gravenwood"] = {d=Pl, l=62, t='D', r=1, R='LMVR',
            c="Eriador/Dunland/Exploring the Gravenwood",
            s={["Rohirrim Scout-camp"]="80.9s,10.6w"},
            p={ {"81.0s,11.2w","The Tree of Tribute"},
                {"80.1s,11.6w","The Mustering Tree"},
                {"80.9s,10.6w","Rohirrim Scout-camp"},
                {"82.8s,9.8w","The Slade of Shadows"},
                {"78.1s,11.4w","Uvel-cadlus"},
                {"80.1s,13.4w","Rhuvel-cadlus"},
                {"84.2s,10.5w","Ak-ghru"},
            },
        },
        ["Heathfells"] = {d=Pl, l=62, t='D', r=1, R='LMVR',
            c="Eriador/Gap of Rohan/Exploring the Heathfells",
            s={["Grimbold's Camp"]="87.8s,3.9w",["Forthbrond"]="86.9s,7.6w"},
            p={ {"87.8s,3.9w","Grimbold's Camp"},
                {"88.4s,6.8w","Dol Baran"},
                {"89.2s,3.7w","River-watch"},
                {"86.1s,3.7w","Pit of Iron"},
                {"51.3n,91.4w","Slave Stockades"},
                {"50.7n,92.4w","The Smelters"},
                {"50.8n,93.0w","The Underworkings"},
            },
        },
        ["Isendale"] = {d=Pl, l=67, t='D', r=1, R='LMVR',
            c="Eriador/Gap of Rohan/Exploring the Isendale",
            s={["Forthbrond"]="86.9s,7.6w"},
            p={ {"87.4s,10.2w","Athdar"},
                {"89.9s,7.6w","Brontrig"},
                {"88.4s,11.5w","Cuvnerth"},
                {"86.0s,7.6w","Forthbrond"},
            },
        },
        ["Gatekeepers of Isengard"] = {d='npc', l=73, t='D', r=1, R='LOTR',
            c="Eriador/Nan Curunir/The Gatekeepers of Isengard",
            s={["Dagoras' Camp"]="84.0s,3.5w"},
            p={ {"81.3s,2.5w","Barashal"},
                {"81.4s,2.5w","Ufdragh"},
            },  
        },
    },
    ["Enedwaith"] = {
        ["Fisher-king"] = {d=Pl, l=59, t='D', r=1, R='LMTVR',
            c="Eriador/Enedwaith/Fisher-king",
            s={["Glyn Helyg"]="62.3s,25.9w",["Lintrev"]="61.7s,24.2w"},
            p={ {"63.2s,24.0w","The Fishing Hole"},
            },
        },
        ["Dwarf-markers"] = {d=, l=, t='', r=1, R='',
            c="",
            s={[""]=""},
            p={ {},
            },
        },
        ["Hobbit Lamp-posts"] = {d=, l=, t='', r=1, R='',
            c="",
            s={[""]=""},
            p={ {},
            },
        },
        ["Hobbit Artifacts"] = {d=, l=, t='', r=1, R='',
            c="",
            s={[""]=""},
            p={ {},
            },
        },
        ["The Grey Company"] = {d=, l=, t='', r=1, R='',
            c="",
            s={[""]=""},
            p={ {},
            },
        },
        ["Homestead of Enedwaith"] = {d=, l=, t='', r=1, R='',
            c="",
            s={[""]=""},
            p={ {},
            },
        },
    },
    ["Ered Luin"] = {
        ["Elf-ruins"] = {},
        ["Places of the Dwarves"] = {},
        ["Rath Teraig"] = {},
        ["Dourhand Camps"] = {},
    },
    ["Eregion"] = {
        ["Dens of the Beasts"] = {},
        ["Campsites of the Fellowship"] = {},
        ["Ruins of Eregion"] = {},
        ["Ring-lore of Eregion"] = {},
    },
    ["Forochel"] = {
        ["Ancient Structurs"] = {},
        ["Gauradan Camps"] = {},
        ["Ancient Treasure"] = {},
    },
    ["Lone-lands"] = {
        ["Ancient Ruins"] = {},
        ["Garth Argawen"] = {},
        ["Grimfens"] = {},
        ["Weathertop"] = {},
    },
    ["Misty Mountains"] = {
        ["Goblin Town"] = {},
        ["Ruins"] = {},
        ["Mountain Peaks"] = {},
        ["Mountain Passes"] = {},
        ["Giant Halls"] = {},
        ["Treasures"] = {},
        ["Bilbo's Buttons"] = {},
    },
    ["North Downs"] = {
        ["Strongholds"] = {},
        ["Eastern Ruins"] = {},
        ["Earth-kin Villages"] = {},
        ["Western Ruins"] = {},
        ["Ancient Treasures"] = {},
    },
    ["Swanfleet & Cardolan"] = {
        ["Dwellers of Old Swanfleet"] = {},
        ["The Many Fold of the Glanduin"] = {},
        ["Perils of Swanfleet"] = {},
        ["Trophy-hunter of Swanfleet"] = {},
        ["Treasure of Swanfleet"] = {},
        ["The Ravaging of Cardolan"] = {},
        ["Inhabitants of the Vanished Realm"] = {},
        ["Perils of Cardolan"] = {},
        ["Treasure of Cardolan"] = {},
        ["Trophy-hunter of Cardolan"] = {},
    },
    ["The Shire"] = {
        ["Farms of the Shire"] = {},
        ["Sights of the Shire"] = {},
        ["Spoiled Pies"] = {},
        ["Quick Post"] = {},
        ["Sites of the Yondershire"] = {},
    },
    ["Trollshaws"] = {
        ["Ruins of the Trollshaws"] = {},
        ["Road to Rivendell"] = {},
        ["Wilds of Tâl Bruinen"] = {},
    },
    ["East Rhohan"] = {
        ["Chambers of Byrgenstow"] = {},
        ["Cities of Eastern Rohan"] = {},
        ["East Wall Explorer"] = {},
        ["Eaves of Fanghorn"] = {},
        ["Enemies of the Rohirrim"] = {},
        ["Farms and Crofts of the Eastemnet"] = {},
        ["Nurseries of the Wyrmdelf"] = {},
        ["Ruins, Tombs, and Monuments of the Easstemnet"] = {},
        ["Defenses of Eastern Rohan"] = {},
        ["Wilds of the Eastemnet"] = {},
        ["Dens"] = {},
    },
    ["The Great River"] = {
        ["Brown Lands Explorer"] = {},
        ["Eorlsmead Explorer"] = {},
        ["Limlight Gorge Explorer"] = {},
        ["Parth Celebrant Explorer"] = {},
        ["Rushgore Explorer"] = {},
        ["Thinglad Explorer"] = {},
        ["Wailing Hills Explorer"] = {},
        ["Stangard Explorer"] = {},
        ["Ancient Ruins of the Limlight"] = {},
        ["Spirits of the Limlight"] = {},
        ["Roots of Fanghorn"] = {},
        ["Slaves of the Spider Queen"] = {},
        ["Defeat Gurthûl"] = {},
    },
    ["Lothlôrien"] = {
        ["Lôrien Look-out"] = {},
        ["Caras Galadhon"] = {},
        ["Wanderer of the Golden Wood"] = {},
    },
    ["Mirkwood"] = {
        ["Strongholds"] = {},
        ["Ruins"] = {},
        ["Towers"] = {},
        ["Ancient Treasures"] = {},
    },
    ["Moria"] = {
        ["Bulwarks of the Enemy"] = {},
        ["In the Footsteps of the Fellowship"] = {},
        ["Mirror Quests"] = {},
        ["A Deep Well"] = {},
        ["Eastern Durin's Way"] = {},
        ["The Cliffs of Zirakzigil"] = {},
        ["Western Durin's Way"] = {},
        ["Orc Camps in Zelem-melek"] = {},
        ["Nud-melek"] = {},
        ["The Great Delving"] = {},
        ["The Redhorn Lodes"] = {},
        ["The Silvertine Lodes"] = {},
        ["Zelem-melek"] = {},
        ["The Flaming Deeps"] = {},
        ["The Foundations of Stone"] = {},
        ["The Water-works"] = {},
    },
    ["West Rohan"] = {
        ["Broadacres"] = {},
        ["Eastfold"] = {},
        ["Kindstead"] = {},
        ["Stonedeans"] = {},
        ["Westfold"] = {},
    },
    ["Wildermore"] = {
        ["Farms"] = {},
        ["Forlawn"] = {},
        ["Whitshaws"] = {},
        ["High Knolls Peaks"] = {},
        ["Settlements"] = {},
        ["The Path of Nurzum"] = {},
        ["Wilds"] = {},
        ["Camps"] = {},
        ["Plants"] = {},
        ["Graveyard"] = {},
    },
    ["Eryn Lasgalen and the Dale-Lands"] = {
        ["Eryn Lasgalen"] = {},
        ["Dale-lands"] = {},
        ["Ruins of the North"] = {},
        ["Dwarf-markers"] = {},
        ["Path of the Company"] = {},
        ["Treasure-seeker of the North"] = {},
        ["3 Scourges"] = {},
    },
    ["Iron Hills"] = {
        ["Iron Veins"] = {},
        ["Survey markers"] = {},
        ["Treasure"] = {},
    },
    ["Ered Mithrin and Withered Heath"] = {
        ["Ruins"] = {},
        ["Iron Veins"] = {},
        ["Dwarf-markers"] = {},
        ["Ancient Dwarf Treasure Cache"] = {},
        ["Dwarf Mining Cache"] = {},
    },
    ["Vales of Anduin"] = {
        ["Chronicle of the Company"] = {},
        ["Enemy encampments"] = {},
        ["Settlements"] = {},
        ["Sites of the Vales"] = {},
        ["Treasure-seeker"] = {},
        ["The Depths of Kidzul-kâlah"] = {},
    },
    ["Wells of Langflood"] = {
        ["Dwarf-markers"] = {},
        ["Natural Formations"] = {},
        ["Ruins"] = {},
        ["Settlements"] = {},
        ["Treasure-seeker"] = {},
        ["Goblin Bounties"] = {},
        ["Askâd-mazal, the Chamber of Sorrows"] = {},
    },
    ["Elderslade"] = {
        ["Amdân Dammul, the Bloody Threshold"] = {},
        ["Ruins"] = {},
        ["Dwarf-markers"] = {},
        ["Enemy Encampments"] = {},
        ["Treasure-seeker"] = {},
    },
    ["Azanulbizar, T.A. 2799"] = {
        ["Azog's Realm"] = {},
        ["Explorer"] = {},
        ["Remnants of Khazad-dûm"] = {},
        ["Fall of Khazad-dûm"] = {},
        ["War-cap of Thrâin"] = {},
        ["Treasure"] = {},
    },
    ["Gundabad"] = {
        ["Crystals"] = {},
        ["Clovengap"] = {},
        ["Enemies of Deepscrave"] = {},
        ["Enemies of Mattugard"] = {},
        ["Scouting the Sorrowglen"] = {},
        ["The Last Frontier of Angmar"] = {},
        ["Treasure of Câr Bronach"] = {},
        ["Gundabad Chests of Câr Bronach"] = {},
        ["Discovering Clovengap"] = {},
        ["The Fall of Forstôri"] = {},
        ["Treasure of Clovengap"] = {},
        ["Gundabad Chests of Clovengap"] = {},
        ["Sites of Deepscrave"] = {},
        ["Treasure of Deepscrave"] = {},
        ["Gundabad Chests of Deepscrave"] = {},
        ["Sites of Stonejaws"] = {},
        ["Treasure of Stonejaws"] = {},
        ["Gundabad Chests of Stonejaws"] = {},
        ["Sites of Mattugard"] = {},
        ["Treasure of Mattugard"] = {},
        ["Gundabad Chests of Mattugard"] = {},
        ["The Cradle of Durin"] = {},
        ["Invaders of the Dark Lake"] = {},
        ["Gundabad Chests of Gloomingtarn"] = {},
        ["Treasure of Gloomingtarn"] = {},
        ["Sites of Welkin-lofts"] = {},
        ["Vistas of Welkin-lofts"] = {},
        ["Treasure of Welkin-lofts"] = {},
        ["Gundabad Chests of Welkin-lofts"] = {},
        ["Invaders on the Dark Lake"] = {},
        ["Trophy-hunter of Gundabad"] = {},
    },
    ["Western Gondor"] = {
        ["Beacons"] = {},
        ["Treasure"] = {},
        ["Paths of the Dead"] = {},
        ["Camps of the Enemies"] = {},
        ["Settlements"] = {},
        ["Roving Threats"] = {},
    },
    ["Central Gondor"] = {
        ["Camps of the Enemies"] = {},
        ["Settlements under seige"] = {},
        ["Path of the Grey Host"] = {},
        ["Pelargir"] = {},
        ["Treasures"] = {},
        ["Roving Threats"] = {},
    },
    ["Eastern Gondor"] = {
        ["Ruins of South Ithilien"] = {},
        ["Strongholds"] = {},
        ["Osgiliath"] = {},
        ["Enemy encampments"] = {},
        ["Beacons"] = {},
        ["Treasure"] = {},
        ["Tribute Baskets"] = {},
        ["Roving Threats"] = {},
    },
    ["Old Anôrien"] = {
        ["Farms"] = {},
        ["Captains"] = {},
        ["Masters"] = {},
        ["Wardens"] = {},
        ["Guild-Halls"] = {},
        ["Roaming Enemies"] = {},
        ["Guests"] = {},
        ["Taverns"] = {},
        ["Teachings"] = {},
        ["Vaults"] = {},
        ["Workings"] = {},
        ["Line of Kings"] = {},
        ["Stewards"] = {},
    },
    ["March of the King"] = {
        ["Beacons"] = {},
        ["Cairns"] = {},
        ["Treasure"] = {},
    },
    ["The Wastes"] = {
        ["Enemy encampments"] = {},
        ["Ranger caches"] = {},
        ["Relics of the Last Alliance"] = {},
        ["Old Gondorian Settlements"] = {},
        ["Roving Threats"] = {},
    },
    ["Eastern King's Gondor"] = {
        ["Reclaiming Lossarnach"] = {},
        ["Reclaiming Upper Lebennin"] = {},
        ["Reclaiming Lower Lebennin"] = {},
        ["Lossarnach"] = {},
        ["Upper Lebennin"] = {},
        ["Lower Lebennin"] = {},
    },
    ["Western King's Gondor"] = {
        ["Belfalas"] = {},
        ["Blackroot Vale"] = {},
        ["Dor-en-Ernil"] = {},
        ["Larnedon"] = {},
        ["Ringlô Vale"] = {},
    },
    ["Outer Gondor"] = {
        ["Anfalas"] = {},
        ["Pinnath Gelin"] = {},
        ["Perils of the Green Hills"] = {},
        ["Perils of Lanstrand"] = {},
    },
    ["Gorgoroth"] = {
        ["Hidden Threats"] = {},
        ["Scourges"] = {},
        ["Forge-fires of Udûn"] = {},
        ["Forge-works of Udûn"] = {},
        ["The Way Into Mordor"] = {},
        ["Ancient Treasures of Udûn"] = {},
        ["Rare Treasures of Udûn"] = {},
        ["Places of Darkness"] = {},
        ["Water Reserves of Dor Arnarth"] = {},
        ["Ancient Treasures of Dor Arnarth"] = {},
        ["Rare Treasures of Dor Arnarth"] = {},
        ["Strongholds of Lhingris"] = {},
        ["Tower of Cirith Ungol"] = {},
        ["Caverns of Lhingris"] = {},
        ["Ancient Treasures of Lhingris"] = {},
        ["Rare Treasures of Lhingris"] = {},
        ["Outposts of Talath Urui"] = {},
        ["Caverns of Fire"] = {},
        ["Water Reserves of Talath Urui"] = {},
        ["Rare Treasures of Talath Urui"] = {},
        ["Ancient Treasures of Talath Urui"] = {},
        ["Landmarks of Agarnaith"] = {},
        ["Courtyards and Terraces of Agarnaith"] = {},
        ["Ancient Treasures of Agarnaith"] = {},
        ["Rare Treasures of Agarnaith"] = {},
        ["Dangerous Foes"] = {},
    },
    ["Imlad Morgul"] = {
        ["Cirith Ungol"] = {},
        ["Rare Treasure of Cirith Ungol"] = {},
        ["Minas Morgul"] = {},
        ["Rare Treasure of Minas Morgul"] = {},
        ["Rath Duath"] = {},
        ["Rare Treasure of Rath Duath"] = {},
        ["Thuringwath"] = {},
        ["Rare Treasure of Thuringwath"] = {},
        ["Second-Age Mordor"] = {},
        ["Rare Treasure in Mordor Beseiged"] = {},
        ["The Nine"] = {},
    },
    ["The Shield Isles"] = {
        ["Denizens"] = {},
        ["Perils"] = {},
        ["Treasure Chests"] = {},
    },
    ["Cape of Umbar"] = {
        ["Citizens"] = {},
        ["Dangers"] = {},
        ["Treasure Chests"] = {},
    },
    ["Umbar Baharbêl"] = {
        ["Places of Umbar Baharbêl"] = {},
        ["False Church of Ordâkh"] = {},
        ["Gates of Umbar Baharbêl"] = {},
        ["Guild Halls of Umbar Baharbêl"] = {},
        ["Taverns of Umbar Baharbêl"] = {},
        ["Markets of Umbar Baharbêl"] = {},
        ["Relcaiming Dil-irmiz"] = {},
        ["Relaiming Ilmabiri"] = {},
        ["Reclaiming Kamrabezûr"] = {},
        ["Reclaiming Tâkhdar"] = {},
        ["Treasure"] = {},
    },
    ["Ambarûl"] = {
        ["Cliff-diver"] = {},
        ["Dangers"] = {},
        ["Scouting"] = {},
        ["Treasures"] = {},
    },
    ["Imhûlar"] = {
        ["Dangers"] = {},
        ["Scouting"] = {},
        ["Lion's Roar"] = {},
        ["Treasures"] = {},
    },
    ["Khûd Zagin"] = {
        ["Dangers"] = {},
        ["Scouting"] = {},
        ["Treasures"] = {},
    },
    ["Urash Dâr"] = {
        ["Dangers"] = {},
        ["Scouting"] = {},
        ["Treasures of Urash Dâr"] = {},
        ["Treasures of Ikorbân Valley"] = {},
    },
    ["Ale Association"] = {},
    ["Inn-League"] = {},
    ["Lhaid Ogo"] = {
        ["Exploration"] = {},
    },
    ["Explorer of the Great River"] = {
        ["Thinglad"] = {},
        ["Eorlsmead"] = {},
        ["Limlight Gorge"] = {},
        ["Wailing Hills"] = {},
        ["Parth Celebrant"] = {},
        ["Rushgore"] = {},
        ["Brown Lands"] = {},
    },
    ["Discovery"] = {
        ["Exploration"] = {},
    },
}