Seregost = "49.0s,33.0e" 
Sg = "Seregost"
Sgl = "Seregost: "
Tg = "Thikil-gundu"
Gd = "Glimmerdeep"
Nb = "Naerband"
Naerband = "63.8s,18.5e"
HuM,HuML = "Hall under Mtn","14.7n,135.2w"
TU = "Torech Ungol@61.4s,4.6e"
TUn = "Must finish 'She Who Walks in the Darkness' to enter Torech Ungol."
Fg = "Felegoth"
Fix = {["the North"]="Strongholds"}
Pl = "place "
TC = "Treasure Cache"
Tc = "Treasure Chest"
RMC = "Rare Mordor Chest"
Region = { Eriador=1, Rhovanion=2, Gondor=3, Mordor=4, Haradwaith=5 }
Atype = {D="Deed", Q="Quest"}
Reward = { B="Barter items", C="Coins", D="Decor", I="Legendary Item Exp",
		L="LOTRO points", M="Marks", O="Other", R="Reputation", 
		S="Steed Exp.", T="Title", V="Virtue Exp." }

Lore = {
    ["Instances"] = {
        ["Shadows of Angmar"] = {
            ["Urugarth"] = {d=Pl, t='D', r=1, R='LVR',
                c="Instances/Shadows of Angmar/The City of Orcs", 
                p={ {"901n,32.1w","Dushkal's Lair"},
                    {"9.0n,30.2w","Lhugrien's Roost"},
                    {"9.8n,30.1w","Lagmâs' Court"},
                    {"10.5n,31.2w","Fell-water Falls"},
                    {"10.2n,32.1w","Urugarth Kennels"},
                    {"8.8n,30.1w","Asht-shâpol"}
                },
            },
            ["Carn Dûm"] = {d=Pl, t='D', r=1, R='LVR',
                c="Instances/Shadows of Angmar/The Enemy's Stronghold", 
                p={ {"12.2n,34.3w","Slave-pens"},
                    {"11.9n,34.5w","Slave-pens"},
                    {"13.8n,32.6w","Barashal's Domain"},
                    {"12.6n,34.0w","Fell-water Source"},
                    {"11.7n,34.4w","Duvardain Quarter"},
                    {"14.0n,33.5w","Castle of Carn Dûm"},
                    {"14.3n,33.6w","Seat of the Witch King"},
                    {"14.0n,33.6w","Witch King's Watch"},
                },
            },
            ["Idols of Urugarth"] = {d=Pl, t='D', r=1, R='LTR',
                c="Instances/Shadows of Angmar/The Foul Idols of Urugarth",
                p={ {"10.7n,31.5w","North-western Foul Idol"},
                    {"10.3n,31.4w","Northern Foul Idol"},
                    {"9.1n,31.0w","Southern Foul Idol"},
                    {"9.0n,31.7w","South-western Foul Idol"},
                    {"9.0n,31.1w","Central Foul Idol"},
                },
            },
        },
        ["Mines of Moria"] = {
            ["The Grand Stair"] = {d=Pl, t='D', r=2, R='LTR',
                c="Instances/Mines of Moria/Landings of the Grand Stair",
                p={ {"71.8n,139.0w","Cave of the Slumbering Beast"},
                    {"71.9n,138.6w","Gothghaash's Stand"},
                    {"72.6n,138.2w","Throne of Igash"},
                    {"71.8n,137.8w","Nardur's Station"},
                    {"71.2n,137.6w","Highpeak Kennels"},
                },
            },
            ["Missing Dwarves in the Vile Maw"] = {d='npc', t='D', r=2, R='LTR',
                c="Instances/Mines of Moria/Lost to the Deeps",
                p={ {"21.0s,115.4w","Dwarf-miner"},
                    {"20.3s,155.2w","Dwarf-merchant"},
                    {"20.4s,115.2w","Dwarf-adventurer"},
                    {"20.7s,115.0w","Dwarf-warrior"},
                },
            },
        },
    },
    ["Angmar"] = {
        ["Outposts of the Free Peope"] = {d=Pl, l=40, t='D', r=1, R='LMVR',
            c="Eriador/Angmar/Bastions of Hope",
            s={["Aughaire"]="0.2s,39.3w",["Gabilshathûr"]="3.6s,26.5w",["Iorelen's Camp"]="10.6n,15.5w",["Gath Forthnír"]="10.4n,24.0w"},
            p={ {"3.0s,39.1w","Lehmä-koti"},
                {"0.0n,40.0w","Aughaire"},
                {"1.9s,33.2w","Tyrn Lhuig"},
                {"3.6s,26.4w","Gabilshathûr"},
                {"10.8n,24.0w","Gath Forthnír"},
            },
        },
        ["Towers of Despair"] = {d=Pl, l=40, t='D', r=1, R='LMVR',
            c="Eriador/Angmar/The Circle of Despair",
            s={["Gath Forthnír"]="10.4n,24.0w"},
            p={ {"7.8n,23.0w","Minas Caul"},
                {"7.2n,23.2w","Minas Agar"},
                {"6.6n,22.9w","Minas Maur"},
                {"6.4n,22.4w","Minas Angos"},
                {"7.8n,21.8w","Minas Nîr"},
                {"6.6n,21.8w","Minas Deloth"},
                {"7.1n,21.6w","Minas Gularan"},
                {"8.0n,22.4w","Minas Dhem"},
            },
        },
        ["Path to Carn Dûm"] = {d=Pl, l=40, t='D', r=1, R='LMVR',
            c="Eriador/Angmar/The Road to War",
            s={["Aughaire"]="0.2s,39.3w",["Gabilshathûr"]="3.6s,26.5w",["Iorelen's Camp"]="10.6n,15.5w",["Gath Forthnír"]="10.4n,24.0w"},
            p={ {"5.00s,36.6w","Skathmúr"},
                {"0.08n,34.25w","Bail Róva"},
                {"3.20n,30.34w","Bail Boglakh"},
                {"3.38n,27.6w","Mor Maudhúl"},
                {"10.14n,28.10w","Bail Dílas"},
                {"12.007n,29.53w","Gate of Shadows"},
            },
        },
        ["Treasure of Angmar"] = {d=Tc, l=40, t='D', r=1, R='LMBVR',
            c="Eriador/Angmar/Treasure of Angmar",
            s={["Gath Forthnír"]="10.4n,24.0w"},
            p={ {"7.2n,30.4w","Imlad Balchorth - across the green death waters. Stepping stones located at 6.7N, 30.5W."},
                {"4.7n,29.2w","Imlad Balchorth - top of the stairs next to Iron Crown Spirit-master"},
                {"3.9n,39.9w","Nád Nathair - behind Bloodwing"},
                {"6.3n,37.9w","Dûn Covád - by War-Master Ranghâsh"},
                {"12.2n,29.5w","Gate of Shadows"},
                {"12.1n,27.3w","Himbar - hole in wall west of entrance to spider area"},
                {"13.0n,25.4w","Torech-i-Bogbereth"},
                {"9.5n,22.9w","Nan-Gurth - north end of path. Main path towards Minas Caul; 8.1N, 23.1W take the narrow path to your left. Follow north to Dourhands, at fork, go right."},
                {"4.5n,21.1w","Nun-Gurth - end of dead-end ledge on south wall"},
                {"1.6s,23.2w","Gorothlad - rim SW of Krusle Lannan"},
                {"0.7s,36.5w","Ram Dúath - end of Cavern with Blade Beaks - follow path S from Aughaire to 1.9S, 39.0W, go downhill E towards lake, E with lake to right to get to cavern."},
                {"10.3n,14.3w","E of Iorelen's Camp near cliff and Orc Camp"},
            },
        },
        ["The Seven Swords"] = {d="sword", l=40, t='Q', r=1, R='LMTR',
        s={["Gabilshathur"]="3.6s,26.5w"},
            c="Eriador/Angmar/The Seven Swords",
            p={ {"1.8n,24.6w","Sword of Abb from Owen"},
                {"2.2n,25.6w","Sword of Kolmak from Ruraikh"},
                {"2.3n,27.8w","Sword of Ánraig from Tobaid"},
                {"3.7n,27.4s","Sword fo Guinokh from Brekhin"},
                {"0.6s,26.2w","Sword of Innis from Dugald"},
                {"0.9s,24.9w","Sword of Kevoka from Frangan"},
                {"0.4s,24.5w","Sword of Mánas from Huisdán"},
            },
        },
        ["Roving Threats"] = {d='npc', l=40, t='Q', r=1, R='LMBTVR',
            c="Eriador/Angmar/Roving Threats: Angmar's Roving Enemies",
            s={["Aughaire"]="0.2s,39.3w",["Gabilshathur"]="3.6s,26.5w",["Iorelen's Camp"]="10.6n,15.5w",["Gath Forthnir"]="10.4n,24.0w"},
            p={ {"0.6n,35.9w","Fasach-larran - E of entrance to Morfil, S cliff"},
                {"4.8n,34.7w","Fasach-Falroid - NE of entrance to Bûrzum Pushdug"},
                {"2.2n,32.0w","N edge of Western Malenhad"},
                {"8.8n,28.7w","SW Himbar - near overlook of Imlad Balchorth"},
                {"0.8n,28.6w","Eastern Malenhad - W shore of lake Duvuinen"},
                {"0.9n,27.2w","Lake Duvuinen - island with Amardam"},
                {"11.3n,27.1w","N Himbar - near spider pit"},
                {"3.2n,24.2w","NE of Grishbalt - drop-off overlooking camp - approach from E"},
                {"5.7n,23.4w","SW Nan Gurth"},
                {"0.8n,20.8w","Gorothlad - E rim of Warg Pit"},
                {"7.1n,201.w","E Nan Gurth - E of Barad Gúlaran"},
            },
        },
        ["Hidden Threats"] = {d='npc', l=40, t='D', r=1, R='TR',
            c="Eriador/Angmar/Hidden Threats of Angmar",
            p={ {"13.0n,25.5w","Spider Lair of Torech-i-Bogbereth"},
                {"6.3n,29.6w","Barrow-grounds of Gurthlin"},
            },
        },
    },
    ["Bree-land"] = {
        ["Barrow Downs"] = {d=Pl, l=20, t='D', r=1, R='LMVR',
            c="Eriador/Bree-Land/The Barrow-downs",
            s={["West Bree"]="29.5s,52.7w"},
            p={ {"30.3s,56.0w","Northern Barrows"},
                {"32.1s,55.1w","The Dead Spire"},
                {"32.1s,53.8w","The Dead Man's Perch"},
                {"33.8s,55.8w","The Great Barrow"},
                {"35.6s,53.9w","Ost Gorthad"},
            },
        },
        ["The Old Forest"] = {d=Pl, l=15, t='D', r=1, R='LMVR',
            c="Eriador/Bree-Land/The Old Forest",
            s={["Adso's Camp"]="29.2s,56.6w",["Buckland"]="32.9s,61.8w"},
            p={ {"31.5s,59.0w","Bald Hill"},
                {"36.8s,57.8w","The Weaver's Den"},
                {"32.6s,57.3w","Tom Bombadil's House"},
                {"31.1s,59.4w","Goldberry's Spring"},
                {"32.8s,60.7w","Bonfire Glade"},
            },
        },
        ["Bree-Land"] = {d=Pl, l=1, t='D', r=1, R='LMVR',
            c="Eriador/Bree-Land/The Ruins of Bree-land",
            s={["Bronwe's Folly"]="28.6s,49.5w",["Adso's Camp"]="29.2s,56.6w",["Buckland"]="32.9s,61.8w",["West Bree"]="29.5s,52.7w",["Hengstacer Farm"]="22.3s,52.3w",["Combe"]="28.6s,49.5w",["South Bree"]="31.9s,50.4w"},
            p={ {"26.8s,48.0w","Bronwe's Folly"},
                {"26.7s,46.6w","Blackwold's Roost"},
                {"27.8s,58.7w","Hillshire Ruins"},
                {"24.0s,53.1w","The Old Greenway Fort"},
                {"26.6s,44.4w","Blackwold Headquarters"},
                {"29.4s,45.9w","Woodsedge Ruins"},
                {"33.3s,48.4w","Ost Baranor"},
                {"33.1s,42.9w","Goblinhole Ruins"},
                {"35.7s,51.5w","South-guard Ruins"},
            },
        },
        ["Flowers of Old Forest"] = {d='flower', l=15, t='D', r=1, R='LMVR',
            c="Eriador/Bree-land/Flowers of the Old Forest",            
            s={["Adso's Camp"]="29.2s,56.6w",["Buckland"]="32.9s,61.8w"},
            p={ {"32.0s,61.0w","Rhosthon's Flower"},
                {"30.6s,57.3w","Neldorlas' Flower"},
                {"34.2s,60.1w","Dorollin's Flower"},
                {"32.6s,59.3w","Cordofoneth's Flower"},
                {"33.3s,57.5w","Lenhwest's Flower"},
                {"35.2s,56.9w","Silloth's Flower"},
                {"32.2s58.4w", "Braiglad's Flower"},
                {"35.3s,58.3w","Merillif's Flower"},
            },
        },
        ["History of the Dúnedain"] = {d='relics', l=1, t='D', r=1, R='LMVR',
            c="Eriador/Bree-land/The History of the Dúnedain",
            s={["Bronwe's Folly"]="28.6s,49.5w",["Adso's Camp"]="29.2s,56.6w",["Buckland"]="32.9s,61.8w",["West Bree"]="29.5s,52.7w",["Hengstacer Farm"]="22.3s,52.3w",["Combe"]="28.6s,49.5w",["South Bree"]="31.9s,50.4w"},
            p={ {"33.4s,48.8w","Ost Baranor - Dúnedain Statue"},
                {"30.2s,49.1w","The Crumbled Court - Ancient Inscription"},
                {"27.1s,46.6w","Blackwold's Roost - Ancient Cairn"},
                {"30.7s,52.6w","Beggar's Alley - Bree - Ancient Crest"},
                {"31.2s,44.9w","Marshwater Fort - Ancient Altar"},
                {"29.5s,45.8w","Woodsedge Ruins - Ancient Obelisk"},
            }
        },
        ["Executioner of the Wicked"] = {d='npc', l=15, t='D', r=1, R='LTR',
            c="Eriador/Bree-land/Executioner of the Wicked",
            s={["West Bree"]="29.5s,52.7w"},
            p={ {"33.0s,55.4w","Hadh Nogbenn - Brishzel"},
                {"31.3s,54.7w","Ringdor - Umnen"},
                {"35.1s,55.1w","Haudh Iarchith - Fergandir"},
                {"33.7s,53.9w","Goetham - Faegfaer"},
                {"31.5s,55.5w","Haudh Methernil - Marrow"},
                {"30.9s,55.0w","Taradan - Gwigon"},
            },
        },
    },
    ["Dunland"] = {
        ["Carreglyn"] = {d=Pl, l=62, t='D', r=1, R='LMVR',
            c="Eriador/Dunland/Exploring Carreglyn",
            s={["Barnavon"]="84.7s,16.3w"},
            p={ {"84.9s,16.8w","Lower Barnavon"},
                {"84.9s,17.6w","Upper Barnavon"},
                {"81.9s,15.7w","Naur-maudhûl"},
                {"84.7s,14.4w","Barnavon Mine"},
                {"85.1s,15.1w","Hen Turrau"},
                {"86.0s,17.4w","Lhun Avanc"},
                {"83.9s,16.8s","Munfaeril's Shrine"},
            },
        },
        ["Pren Gwydh"] = {d=Pl, l=67, t='D', r=1, R='LMVR',
            c="Eriador/Dunland/Exploring Pren Gwydh",
            s={["Galtrev"]="79.9s,16.7w"},
            p={ {"79.2s,17.0w","The Fanged Lair"},
                {"80.2s,18.7w","Bloodtusk's Den"},
                {"78.9s,15.7w","The Galtrev Lumber-camp"},
                {"79.9s,19.5w","Dragon-clan Settlement"},
                {"78.2s,13.8w","The Howling Caverns"},
                {"79.5s,19.0w","Rook's Hut"},
            },
       },
        ["Starkmoor"] = {d=Pl, l=69, t='D', r=1, R='LMVR',
            c="Eriador/Dunland/Exploring Starkmoor",
            s={["Avardin"]="83.5s,20.4w"},
            p={ {"83.4s,20.7w","Avardin"},
                {"81.7s,18.2w","Flam-cadius"},
                {"81.3s,21.3.w","Cartrev Andras"},
                {"84.4s,18.9w","The Hound's Rest"},
                {"83.3s,21.4w","The Culling Pit"},
                {"87.7s,17.3w","Wulf's Cleft Overlook"},
            },
        },
        ["Bonevales"] = {d=Pl, l=62, t='D', r=1, R='LMVR',
            c="Eriador/Dunland/Exploring the Bonevales",
            s={["Echad Naeglanc"]="77.3s,15.8w"},
            p={ {"76.8s,15.0w","The Bone Quarry"},
                {"76.1s,14.3w","Plas-maru"},
                {"77.3s,15.8w","Echad Naeglanc"},
                {"76.7s,18.2w","Lhan Bach"},
                {"75.8s,17.5w","Lhan Gogledh"},
            },
        },
        ["Dunbog"] = {d=Pl, l=62, t='D', r=1, R='LMVR',
            c="Eriador/Dunland/Exploring the Dunbog",
            s={["Lhan Rhos"]="86.8s,23.0w"},
            p={ {"84.0s,24.4w","Lhan Colvarn"},
                {"87.2s,23.2w","Lhan Rhos"},
                {"88.8s,23.81","The Withered Stones"},
                {"88.0s,25,7w","Durgors"},
                {"85.5s,25.7w","The Pristine Glade"},
            },
        },
        ["Trum Drengh"] = {d=Pl, l=66, t='D', r=1, R='LMVR',
            c="Eriador/Dunland/Exploring Trum Dreng",
            s={["Lhan Tarran"]="75.3s,22.4w"},
            p={ {"76.9s,23.0w","Dire Hollow"},
                {"79.2s,24.0w","The Herd-lands"},
                {"75.3s,22.7w","Lhan Tarran"},
                {"74.2s,21.4w","The North Pass"},
                {"76.2s,21.4w","The Watch-tower"},
                {"78.3s,21.2w","The White Hand Outpost"},
            },
        },
        ["Nan Curunír"] = {d=Pl, l=66, t='D', r=1, R='LMVR',
            c="Eriador/Dunland/Exploring Nan Curunír",
            s={["Dagoras' Camp"]="84.9s,3.5w"},
            p={ {"81.4s,2.5w","The Gates of Isengard"},
                {"84.9s,3.0w","Piller of the White Hand"},
                {"81.6s,4.8w","Fang-rider's Warren"},
                {"84.3s,1.6w","Blackmarch Fort"},
                {"82.0s,0.7e","Quickbeam's Grove"},
                {"84.9s,3.4w","Dagoras' Camp"},
            },
        },
        ["Gravenwood"] = {d=Pl, l=62, t='D', r=1, R='LMVR',
            c="Eriador/Dunland/Exploring the Gravenwood",
            s={["Rohirrim Scout-camp"]="80.9s,10.6w"},
            p={ {"81.0s,11.2w","The Tree of Tribute"},
                {"80.1s,11.6w","The Mustering Tree"},
                {"80.9s,10.6w","Rohirrim Scout-camp"},
                {"82.8s,9.8w","The Slade of Shadows"},
                {"78.1s,11.4w","Uvel-cadlus"},
                {"80.1s,13.4w","Rhuvel-cadlus"},
                {"84.2s,10.5w","Ak-ghru"},
            },
        },
        ["Heathfells"] = {d=Pl, l=62, t='D', r=1, R='LMVR',
            c="Eriador/Gap of Rohan/Exploring the Heathfells",
            s={["Grimbold's Camp"]="87.8s,3.9w",["Forthbrond"]="86.9s,7.6w"},
            p={ {"87.8s,3.9w","Grimbold's Camp"},
                {"88.4s,6.8w","Dol Baran"},
                {"89.2s,3.7w","River-watch"},
                {"86.1s,3.7w","Pit of Iron"},
                {"51.3n,91.4w","Slave Stockades"},
                {"50.7n,92.4w","The Smelters"},
                {"50.8n,93.0w","The Underworkings"},
            },
        },
        ["Isendale"] = {d=Pl, l=67, t='D', r=1, R='LMVR',
            c="Eriador/Gap of Rohan/Exploring the Isendale",
            s={["Forthbrond"]="86.9s,7.6w"},
            p={ {"87.4s,10.2w","Âthdâr"},
                {"89.9s,7.6w","Brôntrig"},
                {"88.4s,11.5w","Cuvnerth"},
                {"86.0s,7.6w","Forthbrond"},
            },
        },
        ["Gatekeepers of Isengard"] = {d='npc', l=73, t='D', r=1, R='LBTR',
            c="Eriador/Nan Curunir/The Gatekeepers of Isengard",
            s={["Dagoras' Camp"]="84.0s,3.5w"},
            p={ {"81.3s,2.5w","Barashal"},
                {"81.4s,2.5w","Ufdrágh"},
            },
        },
    },
    ["Enedwaith"] = {
        ["Fisher-king"] = {d=Pl, l=59, t='D', r=1, R='LMTVR',
            c="Eriador/Enedwaith/Fisher-king",
            s={["Glyn Helyg"]="62.3s,25.9w",["Lintrev"]="61.7s,24.2w"},
            p={ {"63.2s,24.0w","The Fishing Hole"},
            },
        },
        ["Dwarf-markers"] = {d='marker', l=1, t='D', r=1, R='LMTVR',
            c="Eriador/Enedwaith/Exiles from the Lonely Mountain",
            s={["Harndirion"]="69.4s,13.7w",["Lhanuch"]="66.9s,16.9w",["Echad Dagoras"]="58.5s,14.5w",["Thorin's Hall"]="15.0s,103.7w"},
            p={ {"71.8s,15.6w","Fordh Maru"},
                {"65.7s,8.5w","Nar's Peak"},
                {"65.6s,18.2w","Pool of the King"},
                {"65.2s,16.7w","Araniant"},
                {"57.4s,14.4w","Fordirith"},
                {"13.8s,103.2w","Thorin's Hall - halfway to throne on L, next to hunter trainer and bowyers"},
            },
        },
        ["Hobbit Lamp-posts"] = {d='lamp-post', l=1, t='D', r=1, R='LBTVR',
            c="Eriador/Enedwaith/The Long Road of the Hobbits",
            s={["Brockenborings"]="27.4s,69.1w",["Echad Daervunn"]="66.6s,21.5w",["Lhanuch"]="66.9s,16.9w",["Harndirion"]="69.4s,13.7w",["Maur Tulhau"]="82.9s,23.2w"},
            p={ {"70.8s,19.4w","Unig-pulh"},
                {"66.5s,21.2w","Echad Daervunn"},
                {"63.2s,22.9w","Maur Tuhau"},
                {"27.2s,67.6w","Brockenborings"},
            },
        },
        ["Hobbit Artifacts"] = {d='artifact', l=59, t='D', r=1, R='LBTVR',
            c="Eregion/Enedwaith/Little Wonders",
            s={["Echad Daervunn"]="66.6s,21.5w",["Maur Tulhau"]="62.0s,23.2w"},
            p={ {"64.3s,22.2w","Hobbit-arrow"},
                {"61.3s,19.2w","Hobbit-boots"},
                {"63.3s,22.2w","Hobbit-bucket"},
                {"63.3s,22.6w","Hobbit-skeleton"},
                {"64.6s,20.4w","Hobbit-pick"},
                {"63.7s,23.0w","Hobbit-bow"},
            },
        },
        ["The Grey Company"] = {d=Pl, l=59, t='D', r=1, R='LMTVR',
            c="Eregion/Enedwaith/Path of the Grey Company",
            s={["Echad Dagoras"]="58.5s,14.5w",["Lhanuch"]="66.9s,16.9w",["Maur Tulhau"]="62.9s,23.2w",["Echad Daervunn"]="66.6s,21.5w",["Harndirion"]="69.4s,13.7w"},
            p={ {"58.5s,14.5w","Echad Dagoras"},
                {"63.8w,17.5w","Echad Saeradan"},
                {"63,5s,21.5w","Echad Idhrenfair"},
                {"66.6s,21.5w","Echad Daervunn"},
                {"69.4s,13.7w","Harndirion"},
            },
        },
        ["Homestead of Enedwaith"] = {d=Pl, l=59, t='D', r=1, R='LMTVR',
            c="Eriador/Enedwaith/The Cartrevs of Enedwaith",
            s={["Echad Dagoras"]="58.5s,14.5w",["Lhanuch"]="66.0s,16.9w"},
            p={ {"59.0s,12.3w","Cartrev Duved"},
                {"67.9s,14.6w","Cartrev Emlun"},
                {"69.4s,17.9w","Cartrev Rurith"},
                {"69.7s,15.3w","Cartrev Matho"},
                {"68.0s,17.0w","Cartrev Hamon"},
            },
        },
        ["Ost Dunhoth"] = {d=Pl, l=60, t='D', r=1, R='O', 
            c="Eriador/Enedwaith/Discoverer of Ost Dunhoth",
            s={["Echad Daervunn"]="66.6s,21.5w",["Lhanuch"]="66.9s,16.9w",["Harndirion"]="69.4s,13.7w"},
            p={"75.2s,19.7w"},
        },
        ["Draigoch's Lair"] = {d=Pl, l=75, t='D', r=1, R='LB',
            c="Eregion/Enedwaith/Draigoch's Lair -- Discovery",
            s={["Lhanuch"]="66.9s,16.9w"},
            p={"67.2s,6.6w"},
        },
        ["Nar's Peak"] = {d=Pl, l=59, t='D', r=1, R='LMTVR',
            c="Eregion/Enedwaith/Master of Stairs",
            s={["Harndirion"]="69.4s,13.7w"},
            p={ {"65.6s,8.5w","climb the stairs to the top"},
            },
        },
    },
    ["Ered Luin"] = {
        ["Elf-ruins"] = {d=Pl, l=1, t='D', r=1, R='LMVR',
            c="Eregion/Ered Luin/Elf-ruins Exploration",
            s={["Celondim"]="28.1s,92.3w",["Duillond"]="24.4s,93.2w",["Thrasi's Lodge"]="21.6s,94.1w"},
            p={ {"29.2s,95.0w","Nen Hilith"},
                {"27.5s,94.4w","Tham Gelair"},
                {"26.6s,95.7w","Limael's Vineyard"},
                {"24.9s,95.0w","Dol Ringwest"},
                {"17.6s,90.1w","The Wardspire"},
            },
        },
        ["Places of the Dwarves"] = {d=Pl, l=1, t='D', r=1, R='LMVR',
            c="Eriador/Ered Luin/Places of the Dwarves",
            s={["Gondamon"]="20.4s,97.1w",["Noglond"]="19.4s,100.6w",["Thorin's Gate"]="15.0s,103.7w"},
            p={ {"15.0.,103.2w","Frerin's Court"},
                {"13.8s,103.2w","Thorin's Gate"},
                {"14.3s,101.7w","Silver Deep Mine"},
                {"19.3s,100.5w","Noglond"},
                {"20.3,97.0w","Gondamon"},
            },
        },
        ["Rath Teraig"] = {d=Pl, l=1, t='D', r=1, R='LMVR',
            c="Eriador/Ered Luin/Rath Teraig Exploration",
            s={["Gondamon"]="20.4s,97.1w"},
            p={ {"22.1s,96.9w","Northern Barricade"},
                {"24.6s,96.7w","Southern Barricade"},
                {"21.6s,96.2w","Tum Agor"},
                {"23.2s,97.3","Amon Thanc"},
                {"24.3s,98.4w","Crookdell"},
            },
        },
        ["Dourhand Camps"] = {d=Pl, l=1, t='D', r=1, R='LMVR',
            c="Eriador/Ered Luin/Scouting the Dourhands",
            s={["Thrasi's Lodge"]="21.6s,94.1w",["Gondamon"]="20.4s,97.1w",["Noglond"]="19.4s,100.6w",["Thorin's Gate"]="15.0s,103.7w"},
            p={ {"17.5s,96.1w","Ringdale"},
                {"17.7s,94.7w","The Grimwater"},
                {"21.3s,92.0w","Spire of Kheledûl"},
                {"21.8s,91.5w","Kheledûl Docks"},
            },
        },
    },
    ["Eregion"] = {
        ["Dens of the Beasts"] = {d=Pl, l=48, t='D', r=1, R='LMVR',
            c="Eriador/Eregion/Dens of the Beasts",
            s={["Gwingris"]="40.2s,16.0w",["Echad Eregion"]="47.0s,12.6w",["Echad Dunann"]="50.6s,7.8w",["Echad Mirobel"]="52.3s,17.0w"},
            p={ {"44.0s,8.8w","Torech Braignel"},
                {"47.1s, 15.2w","Torech Ladnel"},
                {"46.4s,10.4w","Torech Bornagol"},
                {"49.1s,10.5w","Burnt Tor"},
                {"48.2s,12.4w","Sâd Umroval"},
                {"50.7s,9.6w","Torech Andraug"},
                {"56.0s,14.4w","Ulundín"},
            },
        },
        ["Campsites of the Fellowship"] = {d=Pl, l=48, t='D', r=1, R='LMVR',
	        c="Eriador/Eregion/The Ring Goes South",
	        s={["Gwingris"]="40.2s,16.0w",["Echad Eregion"]="47.0s,12.6w",["Echad Dunann"]="50.6s,7.8w",["Echad Mirobel"]="52.3s,17.0w"},
	        p={	{"49.1s,10.5w","Burnt Tor"},
                {"46.7s,2.7w","Caradhras campfire"},
                {"50.6s,7.6w","Sirannon Gate"},
                {"43.8s,12.9w","High Hollin campsite"},
                {"45.9s,8.7w","Tâl Caradhras campsite"},
            },
	    },
        ["Ruins of Eregion"] = {d=Pl, l=55, t='D', r=1, R='LMVR',
            c="Eriador/Eregion/The Ruins of Eregion",
            s={["Gwingris"]="40.2s,16.0w",["Echad Eregion"]="47.0s,12.6w",["Echad Dunann"]="50.6s,7.8w",["Echad Mirobel"]="52.3s,17.0w"},
            p={	{"40.0s,16.2w","Gwingris"},
                {"46.9s,12.5w","Echad Eregion"},
                {"52.5s,16.7w","Erad Mirobel"},
                {"50.5s,7.9w","Echad Dúnann"},
                {"44.1s,10.8w","Pembar"},
                {"48.1s,13.7w","Barad Morlas"},
            },
	    },
        ["Ring-lore of Eregion"] = {d='pages', l=40, t='D', r=1, R='LMTVR',
            c="Eriador/Eregion/Ring-lore of Eregion",
            p={	{"42.4s,13.9w","Worn pages - dropped by Dunlendings"},
                {"42.2s,12.7w","Worn pages - dropped by Dunlendings"},
                {"44.1s,11.0w","Mouldering pages - dropped by Half-orcs"},
                {"44.1s,11.0w","Crumbling pages - looting rubble"},
                {"47.9s,13.0w","Fragile pages - looting rubble"},
                {"52.4s,16.8w","Brittle pages - looting rubble"},
                {"39.6s,16.4w","Delicate pages - looting rubble"},
            },
        },
        ["Uruk-Captains"] = {d='npc', l=40, t='D', r=1, R='LMTVR',
            c="Eriador/Eregion/Uruk-captains of Eregion",
            p={	{"42.3s,16.4w","Tawarond - Logon"},
                {"44.1s,10.7w","Pembar - Fauldush"},
                {"47.9s,13.9w","Barad Morlas - Shatogtar"},
                {"45.7s,7.1w","Cirith Narugorch - Pizumu the Spy-master"},
                {"48.4s,5.5w","Târ Stazg - Akashpug, Chief of Târ Stazg"},
                {"53.4s,9.6w","Porth Cadlus - Gâmzhurm, Lord of Port Cadlus"},
                {"54.2s,11.2w","Emyn Naer - Râkhuga the Tracker"},
            },
        },
    },
    ["Evendim"] = {
        ["Plaques"] = {d='plaques', l=39, t='D', r=1, R='LMTR',
            c="Eriador/Evendim/Markers of the Sunken City",
            s={["Annúminas"]="19.2s,70.9w"},
            p={	{"18.9s,70.8w","Plaque of Echad Garthadir"},
                {"19.0s,68.7w","Placue of Clorhir"},
                {"17.3s,69.4w","Plaque of Ariant"},
                },
        },
        ["Ruins"] = {d=Pl, l=30, t='D', r=1, R='LMVR',
            c="Eriador/Evendim/Ruins of Evendim",
            s={["Oatbarton"]="23.4s,67.4w",["Annúminas"]="19.1s,70.9w",["Dwaling"]="20.8s,64.7w",["High King's Crossing"]="13.8s,64.0w",["Tinnudir"]="12.4s,67.2w",["Ost Forod"]="8.2s,64.3w"},
            p={	{"12.1s,65.6w","Tham Nambarth"},
                {"12.1s,63.9w","Tham Varan"},
                {"11.2s,61.6w","Ost Heryn"},
                {"9.5s,63.1w","Tham Andalath"},
                {"8.7s,66.7w","Tham Ornen"},
                {"7.3s,66.6w","Barad Rath"},
                {"7.2s,69.6w","Rantost"},
                {"11.4s,71.9w","Tollobel"},
            },
        },
        ["Tombs"] = {d=Pl, l=30, t='D', r=1, R='LMVR',
            c="Eriador/Evendim/Tombs of Evendim",
            s={["Dwaling"]="20.8s,64.7w",["High King's Crossing"]="13.8s,64.0w"},
            p={	{"15.9s,66.4w","Haudh Eärendur"},
                {"16.3s,66.0w","Haudh Elendur"},
                {"16.4s,66.5w","Haudh Valandur"},
                {"16.7s,67.0w","Haudh Elendil"},
                {"16.9s,66.1w","Haudh Tarondor"},
                {"17.2s,66.8w","Haudh Eldacar"},
                {"17.1s,66.0w","Haudh Tarcil"},
                {"17.2s,66.3w","Haudh Arantar"},
            },
        },
        ["Wilds"] = {d=Pl, l=30, t='D', r=1, R='LMVR',
            c="Eriador/Evendim/Wilds of Evendim",
            p={	{"7.7s,61.8w","Nan Orngon"},
                {"4.4s,65.2w","Tûm Fuin"},
                {"3.7s,69.5w","The Even-rills"},
                {"6.1s,72.8w","The Eavespires"},
                {"5.8s,72.8w","The Eave-mere"},
                {"7.0s,74.5w","Swiftbrook"},
                {"11.5s,75.1w","The Twisted Grove"},
                {"13.7s,75.8w","Rushingdale"},
            },
        },
        ["Annúminas"] = {d=Pl, l=30, t='D', r=1, R='LMVR',
            c="Eriador/Evendim/The City of the Kings",
            s={["Annúminas"]="19.1s,70.9w"},
            p={	{"17.8s,70.2w","Gwaelband"},
                {"18.4s,71.4w","Gaerannon"},
                {"19.0s,70.9w","Echad Gartadir"},
                {"19.6s,70.1w","Menelband"},
                {"19.0s,68.7w","Clorhir"},
                {"18.5s,68.7w","Tirband"},
                {"17.4s,69.4w","Ariant"},
                {"17.6s,68.5w","Minathranc"},
            },
        },
        ["Treasures"] = {d=TC, l=90, t='D', r=1, R='LMBTVR',
            c="Eriador/Evendim/Treasure of Evendim",
            p={	{"11.9s,72.3w","Tyl Ruinen - top of hill in middle"},
                {"13.8s,73.6w","Tyl Ruinen - small island in SW"},
                {"8.1s,75.3w","Amon Môth"},
                {"7.5s,68.3w","E of Rantost - shore"},
                {"8.7s,67.0w","Tham Ornen - outside of W wall"},
                {"4.2s,65.6w","Tûm Fuin - in bushes"},
                {"7.9s,61.8w","Nan Orngon - top of mountain"},
                {"9.4s,63.0w","Tham Andalath - behind totem"},
                {"20.2s,60.7w","Barandalf - E shore"},
                {"19.7s,64.6w","Whitshards - behind on a hill"},
                {"17.2s,65.6w","Haudh Tarcil in Men Erain - small camp behind"},
                {"15.8s,69.9w","Tul Annûn - L around edge from the Titan of Tyl Annûn"},
            },
        },
        ["Angmarim leaders in Annúminas"] = {d='npc', l=30, t='D', r=1, R='LTR',
            c="Eriador/Evendim/Leaders of the Invasion",
            p={	{"18.3s,69.1w","Agarochir"},
                {"18.5s,68.7w","Agarochir - alternate location (Tirband)"},
                {"19.8s,70.1w","Guldurchir"},
                {"17.7s,69.7w","Siridán"},
                {"17.8s,70.2w","Siridán - alternate location"},
                {"18.8s,69.0w","Unagh Clorhir"},
                {"19.2s,69.1w","Clorhir - alternate location"},
                {"18.2s,70.6w","Valtair"},
            },
        },
        ["Roving Threats"] = {d='npc', l=90, t='Q', r=1, R='LBMTVR',
            c="Eriador/Evendim/Roving Threats: Evendim's Roving Enemies",
            p={"6.1s,73.9w","9.0s,74.1w","4.9s,68.5w","5.8s,61.4w","15.3s,64.4w","16.7s,64.1w","18.6s,70.2w"
            },
        },
    },
    ["Forochel"] = {
        ["Ancient Structures"] = {d=Pl, l=44, t='D', r=1, R='LMVR',
            c="Eriador/Forochel/Ancient Stones of Forochel",
            p={ {"20.0n,85.0w","Kibilzahar"},
                {"17.0n,59.3w","The Ironspan"},
                {"9.5n,81.1w","Zigilgund"},
                {"13.6n,74.4w","The Lonesome Stones"},
                {"8.9n,81.9w","Icreave Mines"},
            },
        },
        ["Gauradan Camps"] = {d=Pl, l=44, t='D', r=1, R='LMVR',
            c="Eriador/Forochel/The Battle for Forochel",
            p={ {"18.8n,81.3w","Hylje-leiri"},
                {"12.9n,66.3w","Karhu-leiri"},
                {"8.8n,70.5w","Mynti-leiri"},
                {"8.0n,78.9w","Norsu-leiri"},
            },
        },
        ["Ancient Treasure"] = {d=Tc, l=44, t='D', r=1, R='LMBTVR',
            c="Eriador/Forochel/Treasure of Forochel",
            p={ {"20.2n,74.1w","NW of boat to Sâri-surma"},
                {"15.7n,68.1w","Isle in the Bay - approach from E to avoid one-shot areas"},
                {"10.4n,65.7w","Itä-mâ - behind rocks across snowfield"},
                {"12.6n,69.7w","Pynti-peldot - bluff near water"},
                {"13.9n,75.4w","Lonesome Stones - far W ruin"},
                {"9.0n,70.8w","Pynti-leiri - behind tent at top"},
                {"4.9n,77.3w","Kissa-sari - SE where river flows off map"},
                {"6.2n,79.7w","Kissa-sari - NW tip"},
                {"8.1n,78.9w","Norsu-leiri - approach from E"},
                {"9.2n,82.2w","NW of Zigilgun - winter-worm area on SW bank of channel near falls"},
                {"15.6n,88.2w","N of Jotunstath - along mountain wall"},
                {"20.1n,85.2w","Kibilzahar - top of W wall at entrance"},
            },
        },
        ["Roving Threat"] = {d='npc', l=90, t='Q', r=1, R='LMBTVR',
            c="Eriador/Forochel/Roving Threats: Forochel's Roving Enemies",
            p={"5.5n,74.5w","7.8n,77.0w","8.1n,76.9w","10.5n,73.0w","14.2n,74.4w","12.3n,66.7w","10.8n,79.5w","12.6n,80.4w","16.7n,86.3w","18.8n,84.5w","20.6n,69.4w","17.7n,67.0w"},
        },
        ["Discoverer"] = {d=Pl, l=44, t='D', r=1, R='O',
            c="Eriador/Forochel/Discoverer of Sâri-surma",
            p={"19.5n,73.8w"},
        },
    },
    ["Lone-lands"] = {
        ["Ancient Ruins"] = {d=Pl, l=20, t='D', r=1, R='LMVR',
            c="Eriador/Lone-lands/Defences of the Lone-lands",
            p={ {"35.8s,38.3w","Barad Iachiant"},
                {"34.5s,37.5w","Ost Laden"},
                {"34.7s,35.5w","The Lornspan"},
                {"34.7s,34.4w","Mithrenost"},
                {"33.8s,32.7w","Thandobel"},
                {"33.6s,30.9w","Ost Cyrn"},
                {"30.7s,33.9w","Naerost"},
                {"30.9s,31.7w","Amon Ros"},
                {"31.3s,29.6w","Ost Guruth"},
            },
        },
        ["Garth Argawen"] = {d=Pl, l=30, t='D', r=1, R='LMVR',
            c="Eriador/Lone-lands/Garth Agarwen Exploration",
            p={ {"31.2s,27.2w","The Circle of Blood"},
                {"30.5s,25.3w","Nan Dhelu"},
                {"28.0s,25.2w","The Outer Gates"},
                {"28.8s,23.9w","Garth Agarwen Gate"},
                {"28.1,23.1w","Ivar's Crypt"},
                {"29.7s,23.2w","Spring of the Red Maid"},
            },
        },
        ["Grimfens"] = {d=Pl, l=20, t='D', r=1, R='LMVR',
            c="Eriador/Lone-lands/The Grimfens",
            p={ {"37.6s,28.0w","Ost Haer"},
                {"37.9s,29.6w","Nindor"},
            },
        },
        ["Weathertop"] = {d=Pl, l=20, t='D', r=1, R='LMVR',
            c="Eriador/Lone-lands/Weathertop Exploration",
            p={ {"29.4s,37.0w","Echad Sûl"},
                {"31.9s,38.6w","Weatherfoot"},
                {"30.1s,38.6w","Glumhallow"},
                {"31.2s,36.9w","Weathertop"},
            },
        },
    },
    ["Misty Mountains"] = {
        ["Ruins"] = {d=Pl, l=30, t='D', r=1, R='LMVR',
            c="Eriador/Misty Mountains/Ruins of the Misty Mountains",
            p={ {"24.8s,4.0w","Glóin's Camp"},
                {"24.9s,1.9e","Hrithur's Haven"},
                {"21.5s,4.6w","Iskeld's Lookout"},
                {"17.9s,2.2w","The Bitter Stair"},
            },
        },
        ["Mountain Peaks"] = {d=Pl, l=30, t='D', r=1, R='LMVR',
            c="Eriador/Misty Mountains/The Forbidding Heights",
            p={ {"23.3s,3.4e","Cirith Daur"},
                {"20.3s,5.4e","The Black Crack"},
                {"22.0s,8.6e","Dómstoll"},
                {"29.6s,9.1e","Erforgh Cleft"},
                {"26.6s,9.0w","Writhenbores"},
                {"20.s,6.9e","Hrimbarg"},
                {"21.5s,4.5e","Akûltot"},
            },
        },
        ["Mountain Passes"] = {d=Pl, l=30, t='D', r=1, R='LMVR',
            c="Eriador/Misty Mountains/The High Passes",
            p={ {"25.4s,3.5w","Cirith Imladris"},
                {"23.3s,0.2e","Whitcleft"},
                {"26.6s,2.6e","Rakhâs-bizar"},
            },
        },
        ["Giant Halls"] = {d=Pl, l=30, t='D', r=1, R='LMVR',
            c="Eriador/Misty Mountains/Where Giants Dwell",
            p={ {"30.2s,2.7e","The Lornestone"},
                {"31.4s,3.4e","Greybough End"},
                {"30.4s,3.6e","The Giant's Needle"},
                {"30.6s,5.7e","Iorbar"},
                {"28.0s,0.8e","Gabilizan"},
            },
        },
        ["Treasures"] = {d=TC, l=90, t='D', r=1, R='LMBTVR',
            c="Eriador/Misty Mountains/Treasure of the Misty Mountains",
            p={ {"23.8s,2.3w","NW of Frosthyle Pond - up snowy slope"},
                {"23.3s,4.3w","Snárskrith Dell - down frozen river behind bears"},
                {"20.5s,3.4w","Helegrod Treasury - W up bluff and across plain"},
                {"25.1s,0.5w","NW of Gabilazan - in bowl down behind ridge - approach from S"},
                {"23.0s,2.6e","Pinnath Fenui - middle of camp - up a small ravine next to the path up, left side of the path"},
                {"20.8s,5.1e","Vindurhal - NW, follow path staying to L; along ledge above Floid and Dewitt"},
                {"21.8s,8.7e","Dómstoll - L behind ruins"},
                {"23.9s,7.4e","NE Hrimbarg - up E stairs and around a rock to the cliff edge"},
                {"26.1s,9.6e","Ruinuan in the Writhenbores - cave"},
                {"28.3s,6.7e","N of back Giant Halls entrance - cul-de-sac"},
                {"28.5s,4.1e","NW Iorbar - up path"},
                {"31.4s,0.3e","Imlad Norn - behind rocks N of path"},
            },
        },
    },
    ["North Downs"] = {
        ["Strongholds"] = {d=Pl, l=20, t='D', r=1, R='LMVR',
            c="Eriador/North Downs/Strongholds Exploration",
            p={ {"15.0s,50.1w","Nan Wathren Western Pass"},
                {"16.2s,45.9w","Nan Wathren Eastern Pass"},
                {"18.6s,46.3w","Hîgropor"},
                {"16.0s,36.8w","Hîsuk"},
                {"16.6s,36.1w","Tûmat"},
            },
        },
        ["Eastern Ruins"] = {d=Pl, l=20, t='D', r=1, R='LMVR',
            c="Eriador/North Downs/The Eastern Ruins",
            p={ {"9.6s,47.6w","Ost Lagoros"},
                {"7.2s,47.0w","Ost Galumar"},
                {"13.5s,42.6w","Dol Nendír"},
                {"15.2s,43.2w","Merenost"},
                {"7.6s,35.0w","Ost Crithlanc"},
            },
        },
        ["Earth-kin Villages"] = {d=Pl, l=20, t='D', r=1, R='LMVR',
            c="Eriador/North Downs/The Villages of the Earth-kin",
            p={ {"9.3s,39.9w","Rusfold"},
                {"8.8s,33.6w","Fashat Laug"},
                {"11.0s,33.5w","Kar Lak"},
                {"3.0s,39.1w","Lehmä-koti"},
            },
        },
        ["Western Ruins"] = {d=Pl, l=20, t='D', r=1, R='LMVR',
            c="Eriador/North Downs/The Western Ruins",
            p={ {"12.6s,52.8w","Amon Raith"},
                {"11.4s,51.2w","Minas Vrûn"},
                {"8.0s,53.2w","Ost Nuaran"},
                {"8.7s,53.4w","Falconer's Tower"},
                {"8.8s,55.2w","Norbury Gates"},
                {"9.4s,59.3w","Glírost"},
                {"11.2s,59.2w","Tham Lorn"},
            },
        },
        ["Ancient Treasures"] = {d=TC, l=90, t='D', r=1, R='LMBTVR',
            c="Eriador/North Downs/Treasure of the North Downs",
            p={ {"16.4s,53.8w","Trestlebridge - under bridge; go to river level on S side of bridge and cross to N side of river"},
                {"13.7s,51.6w","Tiny island in the small bay"},
                {"9.9s,58.4w","Glirost - hill overlooking"},
                {"6.7s,53.3","E Fornost - near Blogmal Warlord"},
                {"6.9s,47.9w","nook E of waterfall"},
                {"6.0s,43.5w","Kamskut - on hill"},
                {"8.6s,40.1w","N of Rusfold - on hill"},
                {"11.2s,33.7w","Kar Lak - under tent"},
                {"15.4s,36.2w","E Dol Dinen outside Hisuk - hill"},
                {"16.6s,37.5","Dol Dinen - inside Zaukil's tent"},
                {"16.3s,41.0w","SE Taur Gonwaith - behind large outcrop"},
                {"19.2s,46.3w","SE Nan Wathren - behind Drukordh's tent; access area from N near Meluinen"},
            },
        },
        ["Roving Threats"] = {d='npc', l=100, t='D', r=1, R='LBMTVR',
            c="Eriador/North Downs/Roving Threats: The North Downs' Roving Enemies",
            p={"7.0s,53.6w","9.7s,56.2w","11.4s,58.4w","12.2s,57.9w","9.6s,52.3w","12.8s,53.1w","11.0s,47.3w","8.1s,36.2w","8.7s,36.2w"},
        },
    },
    ["Swanfleet & Cardolan"] = {
        ["Dwellers of Old Swanfleet"] = {d='items', l=1, t='D', r=1, R='LTV',
            c="Eriador/Swanfleet/Dwellers of Old Swanfleet",
            p={ {"53.1s,20.8w","Old cornerstone"},
                {"55.8s,19.3w","Curious pendant"},
                {"59.0s,21.0w","Engraved Stone"},
                {"62.5s,26.2w","Well-used fishing rod"},
                {"51.8s,25.9w","Cache of old notes"},
                {"49.0s,23.7","Collection of poetry"},
                {"58.6s,34.5w","Rusted Dagger"},
            },
        },
        ["The Many Folk of the Glanduin"] = {d=Pl, l=1, t='D', r=1, R='LTV',
            c="Eriador/Swanfleet/The Many Folk of the Glanduin",
            p={ {"60.8s,34.7w","Mossward"},
                {"65.1s,29.1w","Clegur"},
                {"54.6s,27.0w","Lhan Garan"},
                {"62.4s,25.9w","Glyn Helyg"},
                {"61.6s,24.2w","Lintrev"},
                {"52.8s,22.4w","Echad Terthas"},
                {"47.2s,19.0w","Idhobel"},
            },
        },
        ["Perils of Swanfleet"] = {d=Pl, l=1, t='D', r=1, R='LTV',
            c="Eriador/Swanfleet/Perils of Swanfleet",
            p={ {"61.5s,33.4w","Howlingstones"},
                {"59.6s,29.6w","Radlaw"},
                {"54.4s,302.w","Fangsettle"},
                {"56.8s,21.6w","Bloodhollow"},
                {"65.6s,26.4w","Cobshollow"},
                {"60.2s,22.2w","Sharmokal"},
                {"54.2s,21.6w","Caras Gelebren"},
                {"48.8s,24.0w","Tham Lasgol"},
                {"51.9s,26.0w","Gwâl Cruban"},
                {"45.5s,19.3w","Tham Celechir"},
            },
        },
        ["Trophy-hunter of Swanfleet"] = {d='npc', l=1, t='D', r=1, R='TV',
            c="Eregion/Swanfleet/Trophy-hunter of Swanfleet",
            p={ {"52.6s,33.0w","Thostmoth(Bog-lurker) - roams shores in the Wadewater"},
                {"47.7s,21.4w","Drindolf(Huorn) - Roams W Eregion between Tham Lasgol and Tham Celechir"},
                {"52.5s,29.1w","Gristbite(Neekerbreeker) - Circles around Neekerbreeker hive in Wadewater"},
                {"60.0s,25.6w","Gnaw(Shrew) - roams N of Glyn Helyg"},
                {"51.7s,25.4w","Stoneback(turtle) - roams ruins of Gwâl Cruban"},
                {"49.6s,25.9w","Nurlúg(worm) - roams rocky outcrops on S side of W Eregion and N across river from Gwâl Cruban"},
            },
        },
        ["Treasure of Swanfleet"] = {d=TC, l=1, t='D', r=1, R='TV',
            c="Eregion/Swanfleet/Treasure of Swanfleet",
            p={ {"54.9s,35.2w","Wadewater - by rock on one of the islands"},
                {"61.6s33.3w","Howlingstones"},
                {"56.9s,28.3w","Brigand camp - in tent; approach from NW"},
                {"64,2s,26.5w","Stoor-vales - base of tree; approach from N"},
                {"51.9s,25.9w","Gwâl Cruban - across from Cache of Old Notes"},
                {"57.7s,25.2w","Top of hill near T-junction towards Stoor-vales"},
                {"60.6s,22.2w", "Sharmokal - by tent on top"},
                {"46.0s,21.8w","W of W Eregion Stable Master - follow stream NW to river - among rocks overlooking river junction on N side"},
                {"53.6s,19.9w","Caras Gelebren - E point of upper level at base of pillar"},
                {"41.6s,17.8w","NE of Tham Celehir, almost to Angle of Mitheithel - do NOT go up river!"},
            },
        },
        ["The Ravaging of Cardolan"] = {d='relics', l=1, t='D', r=1, R='LTVR',
            c="Eregion/Cardolan/The Ravaging of Cardolan",
            p={ {"53.5s,53.5w","Oath Plaque - Gaervarad on second floor"},
                {"39.6s,50.6w","Stone Seat - Dol Ernil throne room"},
                {"44.3s,29.2w","Deadmount Obelisk - plaque on S side"},
                {"44.1s,51.7w","Ashmound Memorial"},
                {"54.3s,40.2w","Quest Chain for Scroll of Luilloth starting at Rhiangar up to Quest: The Deciphered Scroll"},
                {"56.7s,37.4w","Levee Plaque - Tharbad - E of the S part of the bridge, under some arches"},
            },
        },
        ["Inhabitants of the Vanished Realm"] = {d=Pl, l=1, t='D', r=1, R='LTVR',
            c="Eriador/Cardolan/Inhabitants of the Vanished Realm",
            p={ {"54.3s,40.2w","Stonecrop Encampment"},
                {"37.6s,49.8w","Gerwyn's Convoy"},
                {"45.1s,39.5w","Sirlond"},
                {"49.8s,45.0w","Herne"},
                {"43.4s,33.6w","Scurloc Farm"},
                {"47.8s,56.2w","Sarn Ford"},
            },
        },
        ["Perils of Cardolan"] = {d=Pl, l=1, t='D', r=1, R='LTVR',
            c="Eriador/Cardolan/Perils of Cardolan",
            p={ {"42.0s,54.5w","Nettinglade"},
                {"53.6s,53.6w","Gaervarad"},
                {"37.6s,52.0w","Sarch Vorn"},
                {"40.0s,50.7w","Dol Ernil"},
                {"45.9s,49.1w","Wylvenclove"},
                {"42.0s,45.2w","Gond Orchal"},
                {"45.3s,41.8w","Caranost"},
                {"56.2s,38.2w","Tharbad"},
                {"42.1s,36.6w","Hove Farm"},
                {"47.4s,32.0w","Nagenstones"},
                {"49.8s,31.6w","Nimbarth"},
                {"41.1s,31.4w","Haudh Nírui"},
                {"44.5s,29.1w","Amon Firn"},
                {"46.3s,28.7w","Everstead"},
            },
        },
        ["Treasure of Cardolan"] = {d=TC, l=1, t='D', r=1, R='TVR',
            c="Eriador/Cardolan/Treasure of Cardolan",
            p={ {"37.3s,55.5w","S Old Forest - W from Sarch Vorn by Henbran's Cottage"},
                {"38.3s,40.1w","Ruins to the W of the road from Lone-lands to Caranost"},
                {"39.7s,50.5w","Dol Emil near Stone Seat"},
                {"40.6s,31.0w","Haudh Nírui - 1 level down"},
                {"45.0s,53.0w","SW Tyrn Gorthad - upper level of ruin"},
                {"45.9s,27.4w","ENE of Everstead in a ruin in South Downs"},
                {"46.0s,42.1w","SW tower of Caranost - outer edge"},
                {"46.2s,49.8w","Ruddymore - ruin by pond next to Annaethel"},
                {"49.0s,36.1w","Sedgemead - by pillar"},
                {"49.4s,54.5w","Down the road from Sarn Ford by abandoned tower"},
                {"51.1s,36.7w","Sedgemead - circle of pillars"},
                {"54.7s,45.7w","SW of doughnut shaped lake - near pillar in ruins"},
                {"55.7s,36.8w","Tharbad - up tower on top floor"},
            },
        },
        ["Trophy-hunter of Cardolan"] = {d='npc', l=1, t='D', r=1, R='TVR',
            c="Eriador/Cardolan/Trophy-hunter of Cardolan",
            p={ {"54.2s,53.0w","Tarangarn(Auroch) - Gaervarad - patrols clockwize around large rock formation on SE side and E-W on E side"},
                {"46.3s,28.1w","Turch(Boar) - NE side of Everstead - around ruined structure"},
                {"41.4s,49.3w","Withergrip(Decayed) - around closed barrow"},
                {"41.6s,33.5w","Skrizug(Goblin) - Scurloc Farm - North of: between ruins or on a ledge"},
                {"37.3s,53.4w","Crúgaul(Bear) - S Old Forest - circles around"},
                {"49.3s,34.1w","Borhashat(Orc) - Sedgemead - patrolling around"},
                {"41.7s,54.1w","Agerbráth(Spider) - Nettinglade - roams plateaus - does not enter the uppermost plateau, but stays on second level going from W to E through the N"},
                {"42.0s,51.0w","Penthúl(Wight) - stationary around a closed barrow at the ruins"},
                {"46.7s,50.4w","Drugodech(Wolf) - Wylvenclove - patrols SW of lake, can sometimes be on a fallen column or up and down the hill between two large rock formations and the ruins on the top of the hill W of the lake"},
            },
        },
    },
    ["The Shire"] = {
        ["Farms of the Shire"] = {d=Pl, l=1, t='D', r=1, R='LMVR',
            c="Eriador/the Shire/The Farms of the Shire",
            p={ {"31.3s,72.7w","Dora Brownlock's Farm"},
                {"34.3s,64.4w","Bamfurlong"},
                {"33.8s,68.0w","Old Odo's Leaf-farm"},
                {"34.4s,74.4w","South Fields"},
                {"29.5s,72.0w","Appledores"},
                {"31.1s,64.2w","Puddifoot's Fields"},
            },
        },
        ["Sights of the Shire"] = {d=Pl, l=1, t='D', r=1, R='LMVR',
            c="Eriador/the Shire/The Sights of the Shire",
            p={ {"29.9s,71.5w","The Party Tree"},
                {"32.5s,69.9w","Methel-stage"},
                {"33.0s,63.6w","Stocktower"},
                {"27.9s,65.7w","The Quarry"},
                {"30.5s,64.1w","The Bridgefields Wall"},
                {"33.6s,70.4w","The Great Willow"},
            },
        },
        ["Spoiled Pies"] = {d='pies', l=1, t='Q', r=1, R='LMVR',
            c="Eriador/the Shire/No Place for Spoiled Pies",
            p={ {"27.6s,68.1w", "Brockenborings"},
                {"31.0s,65.4w","Budgeford"},
                {"31.8s, 69.7w","Bywater"},
                {"31.7s,68.0w","Frogmorton"},
                {"29.6s,71.6w","Hobbiton"},
                {"32.0s,76.6w","Little Delving"},
                {"34.1s,75.1w","Michel Delving"},
                {"28.1s,75.9w","Needlehole"},
                {"27.8s,66.4w","Scary"},
                {"32.1s,63.7w","Stock"},
                {"33.5s,70.9w","Tuckborough"},
                {"33.3s,65.6w","Woodhall"},
            },
        },
        ["Quick Post"] = {d='mail', l=1, t='Q', r=1, R='LMTVR',
            c="Eriador/the Shire/Restoring the Quick Post",
            p={ {"31.8s,76.7w","Little Delving to Michel Delving"},
                {"33.4s,75.0w","Michel Delving to Waymeet"},
                {"32.8s,73.0w","Waymeet to Needlehole"},
                {"27.1s,75.9w","Needlehole to Michel Delving"},
                {"33.4s,75.0w","Michel Delving to Tuckborough"},
                {"33.0s,70.9w","Tuckborough to Hobbiton"},
                {"31.2s,71.3w","Hobbiton to Overhill"},
                {"28.1s,70.1w","Overhill to Bywater"},
                {"31.8s,69.5w","Pick up quest in Bywater and go to Frogmorton - no mail pickup"},
                {"32.1s,68.2w","Frogmorton to Woodhall"},
                {"33.3s,65.7w","Woodhall to Stock"},
                {"31.5s,63.4w","Stock to Budgeford"},
                {"31.2s,65.4w","Budgeford to Scary"},
                {"27.8s,66.5w","Scary to Brockenborings"},
                {"33.4s,75.0w","Talk to Postmaster Proudfoot to finish quest line. Talk to him once more for final Title"}
            },
        },
        ["Sites of the Yondershire"] = {d=Pl, l=10, t='D', r=1, r='BTVR',
            c="Eriador/the Shire/Sites of the Yondershire",
            p={ {"20.0s,77.1w","Bâr Faroth"},
                {"21.8s,82.3w","Ost Lagorath"},
                {"21.6s,74.4w","Taerhad"},
                {"27.3s,86.4w","Tham Amothir"},
                {"24.0s,82.5w","Gamwich"},
                {"22.1s,78.7w","Long Cleeve"},
                {"26.9s,78.9w","Nobottle"},
                {"26.6s,82.4w","Tighfield"},
                {"19.1s,88.7w","Lhúngobel"},
            },
        },
    },
    ["Trollshaws"] = {
        ["Ruins of the Trollshaws"] = {},
        ["Road to Rivendell"] = {},
        ["Wilds of Tâl Bruinen"] = {},
    },
    ["East Rhohan"] = {
        ["Chambers of Byrgenstow"] = {},
        ["Cities of Eastern Rohan"] = {},
        ["East Wall Explorer"] = {},
        ["Eaves of Fanghorn"] = {},
        ["Enemies of the Rohirrim"] = {},
        ["Farms and Crofts of the Eastemnet"] = {},
        ["Nurseries of the Wyrmdelf"] = {},
        ["Ruins, Tombs, and Monuments of the Easstemnet"] = {},
        ["Defenses of Eastern Rohan"] = {},
        ["Wilds of the Eastemnet"] = {},
        ["Dens"] = {},
    },
    ["The Great River"] = {
        ["Brown Lands Explorer"] = {},
        ["Eorlsmead Explorer"] = {},
        ["Limlight Gorge Explorer"] = {},
        ["Parth Celebrant Explorer"] = {},
        ["Rushgore Explorer"] = {},
        ["Thinglad Explorer"] = {},
        ["Wailing Hills Explorer"] = {},
        ["Stangard Explorer"] = {},
        ["Ancient Ruins of the Limlight"] = {},
        ["Spirits of the Limlight"] = {},
        ["Roots of Fanghorn"] = {},
        ["Slaves of the Spider Queen"] = {},
        ["Defeat Gurthûl"] = {},
    },
    ["Lothlôrien"] = {
        ["Lôrien Look-out"] = {},
        ["Caras Galadhon"] = {},
        ["Wanderer of the Golden Wood"] = {},
    },
    ["Mirkwood"] = {
        ["Strongholds"] = {},
        ["Ruins"] = {},
        ["Towers"] = {},
        ["Ancient Treasures"] = {},
    },
    ["Moria"] = {
        ["Bulwarks of the Enemy"] = {},
        ["In the Footsteps of the Fellowship"] = {},
        ["Mirror Quests"] = {},
        ["A Deep Well"] = {},
        ["Eastern Durin's Way"] = {},
        ["The Cliffs of Zirakzigil"] = {},
        ["Western Durin's Way"] = {},
        ["Orc Camps in Zelem-melek"] = {},
        ["Nud-melek"] = {},
        ["The Great Delving"] = {},
        ["The Redhorn Lodes"] = {},
        ["The Silvertine Lodes"] = {},
        ["Zelem-melek"] = {},
        ["The Flaming Deeps"] = {},
        ["The Foundations of Stone"] = {},
        ["The Water-works"] = {},
    },
    ["West Rohan"] = {
        ["Broadacres"] = {},
        ["Eastfold"] = {},
        ["Kindstead"] = {},
        ["Stonedeans"] = {},
        ["Westfold"] = {},
    },
    ["Wildermore"] = {
        ["Farms"] = {},
        ["Forlawn"] = {},
        ["Whitshaws"] = {},
        ["High Knolls Peaks"] = {},
        ["Settlements"] = {},
        ["The Path of Nurzum"] = {},
        ["Wilds"] = {},
        ["Camps"] = {},
        ["Plants"] = {},
        ["Graveyard"] = {},
    },
    ["Eryn Lasgalen and the Dale-Lands"] = {
        ["Eryn Lasgalen"] = {},
        ["Dale-lands"] = {},
        ["Ruins of the North"] = {},
        ["Dwarf-markers"] = {},
        ["Path of the Company"] = {},
        ["Treasure-seeker of the North"] = {},
        ["3 Scourges"] = {},
    },
    ["Iron Hills"] = {
        ["Iron Veins"] = {},
        ["Survey markers"] = {},
        ["Treasure"] = {},
    },
    ["Ered Mithrin and Withered Heath"] = {
        ["Ruins"] = {},
        ["Iron Veins"] = {},
        ["Dwarf-markers"] = {},
        ["Ancient Dwarf Treasure Cache"] = {},
        ["Dwarf Mining Cache"] = {},
    },
    ["Vales of Anduin"] = {
        ["Chronicle of the Company"] = {},
        ["Enemy encampments"] = {},
        ["Settlements"] = {},
        ["Sites of the Vales"] = {},
        ["Treasure-seeker"] = {},
        ["The Depths of Kidzul-kâlah"] = {},
    },
    ["Wells of Langflood"] = {
        ["Dwarf-markers"] = {},
        ["Natural Formations"] = {},
        ["Ruins"] = {},
        ["Settlements"] = {},
        ["Treasure-seeker"] = {},
        ["Goblin Bounties"] = {},
        ["Askâd-mazal, the Chamber of Sorrows"] = {},
    },
    ["Elderslade"] = {
        ["Amdân Dammul, the Bloody Threshold"] = {},
        ["Ruins"] = {},
        ["Dwarf-markers"] = {},
        ["Enemy Encampments"] = {},
        ["Treasure-seeker"] = {},
    },
    ["Azanulbizar, T.A. 2799"] = {
        ["Azog's Realm"] = {},
        ["Explorer"] = {},
        ["Remnants of Khazad-dûm"] = {},
        ["Fall of Khazad-dûm"] = {},
        ["War-cap of Thrâin"] = {},
        ["Treasure"] = {},
    },
    ["Gundabad"] = {
        ["Crystals"] = {},
        ["Clovengap"] = {},
        ["Enemies of Deepscrave"] = {},
        ["Enemies of Mattugard"] = {},
        ["Scouting the Sorrowglen"] = {},
        ["The Last Frontier of Angmar"] = {},
        ["Treasure of Câr Bronach"] = {},
        ["Gundabad Chests of Câr Bronach"] = {},
        ["Discovering Clovengap"] = {},
        ["The Fall of Forstôri"] = {},
        ["Treasure of Clovengap"] = {},
        ["Gundabad Chests of Clovengap"] = {},
        ["Sites of Deepscrave"] = {},
        ["Treasure of Deepscrave"] = {},
        ["Gundabad Chests of Deepscrave"] = {},
        ["Sites of Stonejaws"] = {},
        ["Treasure of Stonejaws"] = {},
        ["Gundabad Chests of Stonejaws"] = {},
        ["Sites of Mattugard"] = {},
        ["Treasure of Mattugard"] = {},
        ["Gundabad Chests of Mattugard"] = {},
        ["The Cradle of Durin"] = {},
        ["Invaders of the Dark Lake"] = {},
        ["Gundabad Chests of Gloomingtarn"] = {},
        ["Treasure of Gloomingtarn"] = {},
        ["Sites of Welkin-lofts"] = {},
        ["Vistas of Welkin-lofts"] = {},
        ["Treasure of Welkin-lofts"] = {},
        ["Gundabad Chests of Welkin-lofts"] = {},
        ["Invaders on the Dark Lake"] = {},
        ["Trophy-hunter of Gundabad"] = {},
    },
    ["Western Gondor"] = {
        ["Beacons"] = {},
        ["Treasure"] = {},
        ["Paths of the Dead"] = {},
        ["Camps of the Enemies"] = {},
        ["Settlements"] = {},
        ["Roving Threats"] = {},
    },
    ["Central Gondor"] = {
        ["Camps of the Enemies"] = {},
        ["Settlements under seige"] = {},
        ["Path of the Grey Host"] = {},
        ["Pelargir"] = {},
        ["Treasures"] = {},
        ["Roving Threats"] = {},
    },
    ["Eastern Gondor"] = {
        ["Ruins of South Ithilien"] = {},
        ["Strongholds"] = {},
        ["Osgiliath"] = {},
        ["Enemy encampments"] = {},
        ["Beacons"] = {},
        ["Treasure"] = {},
        ["Tribute Baskets"] = {},
        ["Roving Threats"] = {},
    },
    ["Old Anôrien"] = {
        ["Farms"] = {},
        ["Captains"] = {},
        ["Masters"] = {},
        ["Wardens"] = {},
        ["Guild-Halls"] = {},
        ["Roaming Enemies"] = {},
        ["Guests"] = {},
        ["Taverns"] = {},
        ["Teachings"] = {},
        ["Vaults"] = {},
        ["Workings"] = {},
        ["Line of Kings"] = {},
        ["Stewards"] = {},
    },
    ["March of the King"] = {
        ["Beacons"] = {},
        ["Cairns"] = {},
        ["Treasure"] = {},
    },
    ["The Wastes"] = {
        ["Enemy encampments"] = {},
        ["Ranger caches"] = {},
        ["Relics of the Last Alliance"] = {},
        ["Old Gondorian Settlements"] = {},
        ["Roving Threats"] = {},
    },
    ["Eastern King's Gondor"] = {
        ["Reclaiming Lossarnach"] = {},
        ["Reclaiming Upper Lebennin"] = {},
        ["Reclaiming Lower Lebennin"] = {},
        ["Lossarnach"] = {},
        ["Upper Lebennin"] = {},
        ["Lower Lebennin"] = {},
    },
    ["Western King's Gondor"] = {
        ["Belfalas"] = {},
        ["Blackroot Vale"] = {},
        ["Dor-en-Ernil"] = {},
        ["Larnedon"] = {},
        ["Ringlô Vale"] = {},
    },
    ["Outer Gondor"] = {
        ["Anfalas"] = {},
        ["Pinnath Gelin"] = {},
        ["Perils of the Green Hills"] = {},
        ["Perils of Lanstrand"] = {},
    },
    ["Gorgoroth"] = {
        ["Hidden Threats"] = {},
        ["Scourges"] = {},
        ["Forge-fires of Udûn"] = {},
        ["Forge-works of Udûn"] = {},
        ["The Way Into Mordor"] = {},
        ["Ancient Treasures of Udûn"] = {},
        ["Rare Treasures of Udûn"] = {},
        ["Places of Darkness"] = {},
        ["Water Reserves of Dor Arnarth"] = {},
        ["Ancient Treasures of Dor Arnarth"] = {},
        ["Rare Treasures of Dor Arnarth"] = {},
        ["Strongholds of Lhingris"] = {},
        ["Tower of Cirith Ungol"] = {},
        ["Caverns of Lhingris"] = {},
        ["Ancient Treasures of Lhingris"] = {},
        ["Rare Treasures of Lhingris"] = {},
        ["Outposts of Talath Urui"] = {},
        ["Caverns of Fire"] = {},
        ["Water Reserves of Talath Urui"] = {},
        ["Rare Treasures of Talath Urui"] = {},
        ["Ancient Treasures of Talath Urui"] = {},
        ["Landmarks of Agarnaith"] = {},
        ["Courtyards and Terraces of Agarnaith"] = {},
        ["Ancient Treasures of Agarnaith"] = {},
        ["Rare Treasures of Agarnaith"] = {},
        ["Dangerous Foes"] = {},
    },
    ["Imlad Morgul"] = {
        ["Cirith Ungol"] = {},
        ["Rare Treasure of Cirith Ungol"] = {},
        ["Minas Morgul"] = {},
        ["Rare Treasure of Minas Morgul"] = {},
        ["Rath Duath"] = {},
        ["Rare Treasure of Rath Duath"] = {},
        ["Thuringwath"] = {},
        ["Rare Treasure of Thuringwath"] = {},
        ["Second-Age Mordor"] = {},
        ["Rare Treasure in Mordor Beseiged"] = {},
        ["The Nine"] = {},
    },
    ["The Shield Isles"] = {
        ["Denizens"] = {},
        ["Perils"] = {},
        ["Treasure Chests"] = {},
    },
    ["Cape of Umbar"] = {
        ["Citizens"] = {},
        ["Dangers"] = {},
        ["Treasure Chests"] = {},
    },
    ["Umbar Baharbêl"] = {
        ["Places of Umbar Baharbêl"] = {},
        ["False Church of Ordâkh"] = {},
        ["Gates of Umbar Baharbêl"] = {},
        ["Guild Halls of Umbar Baharbêl"] = {},
        ["Taverns of Umbar Baharbêl"] = {},
        ["Markets of Umbar Baharbêl"] = {},
        ["Relcaiming Dil-irmiz"] = {},
        ["Relaiming Ilmabiri"] = {},
        ["Reclaiming Kamrabezûr"] = {},
        ["Reclaiming Tâkhdar"] = {},
        ["Treasure"] = {},
    },
    ["Ambarûl"] = {
        ["Cliff-diver"] = {},
        ["Dangers"] = {},
        ["Scouting"] = {},
        ["Treasures"] = {},
    },
    ["Imhûlar"] = {
        ["Dangers"] = {},
        ["Scouting"] = {},
        ["Lion's Roar"] = {},
        ["Treasures"] = {},
    },
    ["Khûd Zagin"] = {
        ["Dangers"] = {},
        ["Scouting"] = {},
        ["Treasures"] = {},
    },
    ["Urash Dâr"] = {
        ["Dangers"] = {},
        ["Scouting"] = {},
        ["Treasures of Urash Dâr"] = {},
        ["Treasures of Ikorbân Valley"] = {},
    },
    ["Ale Association"] = {},
    ["Inn-League"] = {},
    ["Lhaid Ogo"] = {
        ["Exploration"] = {},
    },
    ["Explorer of the Great River"] = {
        ["Thinglad"] = {},
        ["Eorlsmead"] = {},
        ["Limlight Gorge"] = {},
        ["Wailing Hills"] = {},
        ["Parth Celebrant"] = {},
        ["Rushgore"] = {},
        ["Brown Lands"] = {},
    },
    ["Discovery"] = {
        ["Exploration"] = {},
    },
}
